(()=>{'use strict';
const $=id=>document.getElementById(id),wait=n=>new Promise(r=>setTimeout(r,n));
const PROFESSIONS={warrior:{icon:'⚔️',name:'戰士',desc:'近距離接敵與格位壓迫。'},ranger:{icon:'🏹',name:'遊俠',desc:'保持距離、回身射擊與遠距壓制。'},priest:{icon:'✨',name:'祭司',desc:'治療、守護、復甦與反擊。'}};
class V07BrowserAdapter{
 constructor(){this.runtime=null;this.config=null;this.board=$('board');this.grid=$('grid');this.pieces=$('pieces');this.effects=$('effects');this.noticeEl=$('bossNotice')||null;this.modal=$('modal');this.panel=$('panel');this.anim=window.RPGAnimations?.createAnimator?RPGAnimations.createAnimator({effects:this.effects,step:()=>this.step(this.runtime?.state||{cols:4})}):null}
 attach(runtime){this.runtime=runtime;return this}
 async boot(state,config,runtime){this.attach(runtime);this.config=config;this.buildGrid(state);if(config.preloadHeroes)for(const h of config.preloadHeroes)runtime.spawns.enqueue({type:'hero',...h});else if(!state.units.length)for(let i=0;i<3;i++)runtime.spawns.enqueue({type:'hero',tier:2,special:false});const hs=await runtime.spawns.settle();for(const h of hs)await this.spawnFx(h);this.bindInput();this.bindRuntimeEvents();this.render(state)}
 bindRuntimeEvents(){if(this._eventsBound)return;this._eventsBound=true;const e=this.runtime.events;e.on('UNIT_SPAWNED',async({unit})=>{this.render(this.runtime.state);await this.spawnFx(unit)});e.on('ENEMY_MOVE',async({enemy})=>{this.render(this.runtime.state);await wait(120)});e.on('ENEMY_ATTACK',async({hero,damage})=>{this.anim?.play('slash',{target:hero});if(damage)this.anim?.play('damage',{target:hero,value:damage})});e.on('GUARD_BLOCK',async({hero})=>this.anim?.play('buff',{target:hero,text:'🛡️ -1'}));e.on('PRIEST_GUARD',async({targets})=>{for(const h of targets)this.anim?.play('buff',{target:h,text:'🛡️ -1'})})}
 buildGrid(state){if(!this.grid)return;this.grid.innerHTML='';for(let i=0;i<state.rows*state.cols;i++){const d=document.createElement('div');d.className='cell';this.grid.appendChild(d)}if(this.board)this.board.style.setProperty('--v07-rows',state.rows)}
 step(state){const width=this.pieces?.clientWidth||this.board?.clientWidth||320;return(width-24)/state.cols+8}
 heroValue(h){return Math.max(1,(h.tier||2)/2)} maxHP(u){return this.runtime?.units?.maxHP?.(u)||u.maxHits||1} rem(u){return Math.max(0,this.maxHP(u)-(u.hits||0))}
 inner(u){if(u.type==='hero'){const p=u.special?PROFESSIONS[u.profession]:null;return`${p?'<div class="classBadge">'+p.icon+'</div>':''}${u.guard?'<div class="guardBadge">🛡️</div>':''}<div class="heroNum">${this.heroValue(u)}</div>${window.RPGShared?.healthBar?RPGShared.healthBar(this.rem(u),this.maxHP(u),'hero'):''}`}if(u.type==='boss')return `<div class="icon">🗿</div><div class="name">巨象守衛</div>${window.RPGShared?.healthBar?RPGShared.healthBar(this.rem(u),this.maxHP(u),'boss','ATK '+(u.damage||1)):''}`;return `<div class="icon">🥷</div><div class="name">暗影刺客</div>${u.maxHits>1&&window.RPGShared?.healthBar?RPGShared.healthBar(this.rem(u),u.maxHits,'enemy','ATK '+(u.damage||1)):'<div class="unitMeta">ATK '+(u.damage||1)+'</div>'}`}
 render(state){this.buildGrid(state);if(!this.pieces)return;this.pieces.innerHTML='';const step=this.step(state);for(const u of state.units.filter(x=>!x.dead)){const d=document.createElement('div');d.className='piece '+(u.type==='hero'?'heroUnit'+(u.special?' specialUnit role-'+u.profession:''):u.type==='boss'?'boss':'enemy');d.dataset.id=u.id;d.style.transform=`translate(${u.c*step}px,${u.r*step}px)`;d.innerHTML=this.inner(u);this.pieces.appendChild(d)}if($('score'))$('score').textContent=state.score||0;if($('turn'))$('turn').textContent=state.turn;if($('merges'))$('merges').textContent=state.merges;if($('best'))$('best').textContent=Math.max(1,...state.living('hero').map(h=>this.heroValue(h)));if($('profession'))$('profession').textContent=state.profession?(PROFESSIONS[state.profession]?.icon+' '+PROFESSIONS[state.profession]?.name):'未選擇';if(this.board)this.board.dataset.warningRow=state.warningRow>=0?String(state.warningRow):''}
 bindInput(){if(this._bound||!this.board)return;this._bound=true;if(window.RPGShared?.bindDirectionalInput){RPGShared.bindDirectionalInput({board:this.board,onMove:d=>this.runtime?.playerAction(d),threshold:25,keyMap:{ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}});return}}
 async animateMove(tx,state){const moves=tx.actualMoves||tx.moved||[];if(!moves.length)return true;const s=this.step(state),ghosts=[];for(const m of moves){const unit=state.units.find(x=>x.id===(m.heroId||m.id))||state.units.find(x=>x.id===m.mergedInto);if(!unit)continue;const g=document.createElement('div');g.className='moveghost heroUnit'+(unit.special?' specialUnit role-'+unit.profession:'');g.innerHTML=this.inner(unit);g.style.transform=`translate(${m.from.c*s}px,${m.from.r*s}px)`;this.effects?.appendChild(g);ghosts.push({g,to:m.to})}requestAnimationFrame(()=>requestAnimationFrame(()=>ghosts.forEach(x=>x.g.style.transform=`translate(${x.to.c*s}px,${x.to.r*s}px)`)));await wait(window.RPGShared?.TIMING?.MOVE||180);ghosts.forEach(x=>x.g.remove());this.render(state);return true}
 async spawnFx(unit){if(!unit||!this.effects)return;const s=this.step(this.runtime.state),d=document.createElement('div');d.className='spawnfx '+(unit.type==='hero'?'heroUnit'+(unit.special?' specialUnit role-'+unit.profession:''):unit.type==='boss'?'boss':'enemy');d.style.transform=`translate(${unit.c*s}px,${unit.r*s}px)`;d.innerHTML=this.inner(unit);this.effects.appendChild(d);setTimeout(()=>d.remove(),window.RPGShared?.TIMING?.SPAWN||260);await wait(window.RPGShared?.TIMING?.SPAWN||260)}
 async chooseProfession(){if(this.runtime.state.profession)return this.runtime.state.profession;return new Promise(resolve=>{if(!this.modal||!this.panel){this.runtime.professions.setProfession('warrior');this.runtime.state.nextSpecial=true;resolve('warrior');return}let idx=0,ps=Object.entries(PROFESSIONS);const draw=()=>{const [id,p]=ps[idx];this.panel.innerHTML='<h2>選擇特殊職業</h2><div class="lead">第一次合併 · 本局職業一旦選擇就固定</div><div class="professionTabs">'+ps.map(([k,x],i)=>'<button class="professionTab '+(i===idx?'active':'')+'" data-i="'+i+'">'+x.icon+' '+x.name+'</button>').join('')+'</div><div class="professionSwipe"><div class="professionHero"><span>'+p.icon+'</span><div><h3>'+p.name+'</h3><p>'+p.desc+'</p></div></div><button class="professionSelect" data-id="'+id+'">選擇 '+p.icon+' '+p.name+'</button></div>';this.panel.querySelectorAll('.professionTab').forEach(b=>b.onclick=()=>{idx=Number(b.dataset.i);draw()});this.panel.querySelector('.professionSelect').onclick=b=>{const chosen=b.currentTarget.dataset.id;this.runtime.professions.setProfession(chosen);this.runtime.state.nextSpecial=true;this.modal.classList.remove('show');this.render(this.runtime.state);resolve(chosen)}};this.modal.classList.add('show');draw()})}
 async afterPlayerTurn(){const special=!!this.runtime.state.nextSpecial&&!!this.runtime.state.profession;if(special)this.runtime.state.nextSpecial=false;this.runtime.spawns.enqueue({type:'hero',tier:2,special,profession:special?this.runtime.state.profession:null});await this.runtime.spawns.settle();const turn=this.runtime.state.turn;if(turn%2===0){if(this.runtime.state.skipNextEnemySpawn)this.runtime.state.skipNextEnemySpawn=false;else{const d=Math.ceil(((this.runtime.state.bossDefeats||0)+1)/2);this.runtime.spawns.enqueue({type:'enemy',damage:d,maxHits:d});await this.runtime.spawns.settle()}}this.render(this.runtime.state);return true}
 async expandRows(){return true} async collapseBottomRow(){return true} setWarningRow(){return true} async notice(text){if(this.noticeEl)this.noticeEl.textContent=text;return true}
 skillRank(id){return window.RPGSave?.rankFromUses&&window.RPGSave?.uses?RPGSave.rankFromUses(RPGSave.uses(id)):'LV1'} bossUnit(){return this.runtime?.state.units.find(u=>u.type==='boss'&&!u.dead)||null}
 bossGameAdapter(state,runtime){const self=this;return{rows:()=>state.rows,bossUnit:()=>self.bossUnit(),bossAlive:()=>runtime.units.alive(self.bossUnit()),spawnBossUnit:def=>runtime.spawn.boss({maxHits:10,damage:1,bossId:def.id,name:def.name,icon:def.icon}),findChargeTarget:()=>self.findChargeTarget(),hasAdjacentHero:()=>self.hasAdjacentHero(),charge:line=>self.charge(line),quake:()=>self.quake(),stomp:()=>self.stomp()}}
 findChargeTarget(){const b=this.bossUnit();if(!b)return null;for(const h of this.runtime.state.living('hero')){if(h.r!==b.r&&h.c!==b.c)continue;const dr=Math.sign(h.r-b.r),dc=Math.sign(h.c-b.c);let r=b.r+dr,c=b.c+dc,clear=true;while(r!==h.r||c!==h.c){if(this.runtime.board.at(r,c)){clear=false;break}r+=dr;c+=dc}if(clear)return{hero:h,dr,dc}}return null}
 hasAdjacentHero(){const b=this.bossUnit();return !!b&&V07CombatTargeting.around8(b,this.runtime.state.living('hero')).length>0}
 async charge(line){const b=this.bossUnit();if(!b||!line)return false;for(let i=0;i<2;i++){const nr=b.r+line.dr,nc=b.c+line.dc;if(!this.runtime.board.inBounds(nr,nc))break;const hit=this.runtime.board.at(nr,nc,b.id);if(hit){if(hit.type==='hero')await this.runtime.damage.apply(hit,1,{source:b,kind:'boss-charge'});break}b.r=nr;b.c=nc}this.render(this.runtime.state);return true}
 async quake(){const b=this.bossUnit();if(!b)return false;for(const h of V07CombatTargeting.around8(b,this.runtime.state.living('hero')))await this.runtime.damage.apply(h,1,{source:b,kind:'boss-quake'});return true}
 async stomp(){const b=this.bossUnit(),hs=this.runtime.state.living('hero');if(!b||!hs.length)return false;const h=V07CombatTargeting.nearest(b,hs,1)[0],dr=Math.sign(h.r-b.r),dc=Math.sign(h.c-b.c);if(V07CombatTargeting.distance(b,h)===1){await this.runtime.damage.apply(h,2,{source:b,kind:'boss-stomp'});return true}const nr=b.r+(Math.abs(h.r-b.r)>=Math.abs(h.c-b.c)?dr:0),nc=b.c+(Math.abs(h.r-b.r)<Math.abs(h.c-b.c)?dc:0);if(this.runtime.board.inBounds(nr,nc)&&!this.runtime.board.at(nr,nc,b.id)){b.r=nr;b.c=nc}this.render(this.runtime.state);return true}
}
window.V07BrowserAdapter=V07BrowserAdapter;
})();