(()=>{'use strict';
class V07GameRuntime{
 constructor({mode='normal',config={},adapter,trace}={}){
  if(!adapter)throw new Error('V07GameRuntime requires adapter');this.trace=trace||((event,data)=>console.log('[V07]',event,data||''));this.config=V07GameConfig.get(mode,config);this.state=new V07RuntimeState(this.config);this.adapter=adapter;
  this.events=new V07EventBus((e,d)=>this.trace(e,d));this.board=new V07BoardCore(this.state);this.units=V07UnitRules;this.spawn=new V07SpawnManager({board:this.board});this.move=new V07MoveManager({state:this.state,board:this.board,units:this.units,trace:(e,d)=>this.trace(e,d)});this.mergeEvents=new V07MergeEventManager({state:this.state,trace:(e,d)=>this.trace(e,d),handlers:{onEveryMerge:e=>this.events.emit('MERGE',e),onEveryThirdMerge:e=>this.events.emit('MERGE_3',e)}});this.damage=new V07DamageManager({units:this.units,eventBus:this.events,trace:(e,d)=>this.trace(e,d)});
  this.deaths=new V07DeathManager({state:this.state,board:this.board,units:this.units,eventBus:this.events,rewardBoss:u=>this.adapter.rewardBoss?.(u,this.state,this),onBossDefeated:()=>this.bossDefeated(),trace:(e,d)=>this.trace(e,d)});this.events.on('UNIT_LETHAL',e=>this.deaths.queue(e.target));
  this.mapEvents=new V07MapEventManager({rows:()=>this.state.rows,setWarningRow:r=>{this.state.setWarningRow(r);this.adapter.setWarningRow?.(r)},notice:(...a)=>this.adapter.notice?.(...a),render:()=>this.adapter.render?.(this.state),collapseBottomRow:async()=>{const row=this.state.rows-1,killed=this.board.killRow(row);await this.adapter.collapseBottomRow?.(this.state,killed);this.board.compactDead();this.state.setRows(this.state.rows-1)}},(...a)=>this.trace('MAP',a));this.professions=new V07ProfessionManager({runtime:this,trace:(e,d)=>this.trace(e,d)});this.enemies=new V07EnemyManager({runtime:this,trace:(e,d)=>this.trace(e,d)});this.turnManager=new V07TurnManager({playerPhase:a=>this.playerPhase(a),enemyPhase:()=>this.enemyPhase(),mapEventPhase:()=>this.mapEventPhase(),trace:(...a)=>this.trace('TURN',a)});
 }
 async boot(){this.trace('BOOT',this.state.snapshot());await this.adapter.boot?.(this.state,this.config,this);if(this.config.boss)await this.spawnBoss(this.config.boss);this.adapter.render?.(this.state);return this}
 bossContext(){return{game:this.adapter.bossGameAdapter?.(this.state,this)||this.adapter,mapEvents:this.mapEvents,animations:this.adapter.animations,trace:(e,d)=>this.trace(e,d)}}
 async spawnBoss(id){const boss=V07Bosses.create(id,this.bossContext());this.state.activeBoss=boss;await boss.onSpawn();this.trace('BOSS_READY',{id});return boss}
 async playerPhase(action){this.state.setPhase('PLAYER');const tx=this.move.execute(action);if(!tx.changed)return false;this.state.moves++;await this.adapter.animateMove?.(tx,this.state,this);await this.mergeEvents.resolve(tx);await this.events.emit('AFTER_PLAYER_MOVE',{transaction:tx});await this.deaths.settle();this.state.nextTurn();return tx}
 async enemyPhase(){this.state.setPhase('ENEMY');await this.enemies.run();if(this.state.activeBoss?.isAlive())await this.state.activeBoss.takeTurn();await this.deaths.settle();return true}
 async mapEventPhase(){this.state.setPhase('MAP_EVENT');return this.mapEvents.run()}
 async playerAction(action){if(this.state.ended||this.state.busy)return false;this.state.busy=true;try{return await this.turnManager.runPlayerAction(action)}finally{this.state.busy=false;this.state.setPhase('IDLE');this.adapter.render?.(this.state)}}
 async bossDefeated(){const boss=this.state.activeBoss;if(!boss)return false;const result=await boss.onDefeated();this.trace('BOSS_DEFEATED_SETTLED',{id:boss.id});return result}
}
window.V07GameRuntime=V07GameRuntime;
})();