(()=>{'use strict';
class V07GameRuntime{
 constructor({mode='normal',config={},adapter,trace}={}){if(!adapter)throw new Error('V07GameRuntime requires adapter');this.trace=trace||(()=>{});this.config=V07GameConfig.get(mode,config);this.state=new V07RuntimeState(this.config);this.adapter=adapter;this.events=new V07EventBus((e,d)=>this.trace(e,d));this.board=new V07BoardCore(this.state);this.units=V07UnitRules;this.spawn=new V07SpawnManager({board:this.board});this.spawns=new V07SpawnSettlement({runtime:this,trace:(e,d)=>this.trace(e,d)});this.move=new V07MoveManager({state:this.state,board:this.board,units:this.units,trace:(e,d)=>this.trace(e,d)});this.mergeEvents=new V07MergeEventManager({state:this.state,trace:(e,d)=>this.trace(e,d),handlers:{onEveryMerge:e=>this.events.emit('MERGE',e),onEveryThirdMerge:e=>this.events.emit('MERGE_3',e)}});this.damage=new V07DamageManager({units:this.units,eventBus:this.events,trace:(e,d)=>this.trace(e,d)});this.deaths=new V07DeathManager({state:this.state,board:this.board,units:this.units,eventBus:this.events,rewardBoss:u=>this.adapter.rewardBoss?.(u,this.state,this),onBossDefeated:()=>this.bossDefeated(),trace:(e,d)=>this.trace(e,d)});this.events.on('UNIT_LETHAL',e=>this.deaths.queue(e.target));this.revival=new V07RevivalManager({runtime:this,trace:(e,d)=>this.trace(e,d)});this.skills=new V07SkillSystem({runtime:this,trace:(e,d)=>this.trace(e,d)});this.mastery=new V07MasteryManager({adapter:this.adapter});this.innateMergeCombat=new V07InnateMergeCombat(this).bind();this.commonClassSkills=new V07CommonClassSkills(this,(e,d)=>this.trace(e,d));this.mapEvents=new V07MapEventManager({rows:()=>this.state.rows,setWarningRow:r=>{this.state.setWarningRow(r);this.adapter.setWarningRow?.(r)},notice:(...a)=>this.adapter.notice?.(...a),render:()=>this.adapter.render?.(this.state),expandRows:async count=>{if(count<=0)return;await this.adapter.expandRows?.(count,this.state);this.state.setRows(this.state.rows+count)},collapseBottomRow:async()=>{}},(...a)=>this.trace('MAP',a));this.professions=new V07ProfessionManager({runtime:this,trace:(e,d)=>this.trace(e,d)});this.priestClassSkills=new V07PriestClassSkills(this);this.warriorSkills=new V07WarriorSkills(this).bind();this.rangerSkills=new V07RangerSkills(this).bind();this.enemies=new V07EnemyManager({runtime:this,trace:(e,d)=>this.trace(e,d)});this.turnManager=new V07TurnManager({playerPhase:a=>this.playerPhase(a),enemyPhase:()=>this.enemyPhase(),mapEventPhase:()=>this.mapEventPhase(),mapEventsEnabled:()=>this.config.features?.mapEvents!==false,getTurn:()=>this.state.turn,trace:()=>{}})}
 registerSkills(ds=[]){for(const s of ds)this.skills.register(s);this.skills.load(this.config.preloadSkills||[]);return this}
 async boot(){await this.adapter.boot?.(this.state,this.config,this);if(this.config.features?.boss!==false&&this.config.boss)await this.spawnBoss(this.config.boss);this.adapter.render?.(this.state);return this}
 async playerPhase(action){this.state.setPhase('PLAYER');const tx=this.move.execute(action);if(!tx.changed)return false;this.state.moves++;await this.adapter.animateMove?.(tx,this.state,this);await this.mergeEvents.resolve(tx);await this.events.emit('AFTER_PLAYER_MOVE',{transaction:tx});await this.deaths.settle();if(tx.mergeCount&&!this.state.profession)await this.adapter.chooseProfession?.(this.state,this);this.state.nextTurn();await this.adapter.afterPlayerTurn?.(tx,this.state,this);return tx}
 async enemyPhase(){this.state.setPhase('ENEMY');await this.enemies.run();if(this.config.features?.boss!==false){const boss=this.state.activeBoss;if(boss?.isAlive())await boss.takeTurn()}await this.deaths.settle();await this.spawns.settle();return true}
 async mapEventPhase(){if(this.config.features?.mapEvents===false)return false;this.state.setPhase('MAP_EVENT');return this.mapEvents.run()}
 async playerAction(action){if(this.state.ended||this.state.busy)return false;this.state.busy=true;try{return await this.turnManager.runPlayerAction(action)}finally{this.state.busy=false;this.state.setPhase('IDLE');this.adapter.render?.(this.state)}}
 async spawnBoss(id){if(this.config.features?.boss===false)return null;const boss=V07Bosses.create(id,this.bossContext());this.state.activeBoss=boss;await boss.onSpawn();return boss} bossContext(){return{game:this.adapter.bossGameAdapter?.(this.state,this)||this.adapter,mapEvents:this.mapEvents,trace:(e,d)=>this.trace(e,d)}} async bossDefeated(){if(this.config.features?.boss===false)return false;return this.state.activeBoss?.onDefeated?.()||false}
}
window.V07GameRuntime=V07GameRuntime;
})();