(function(){'use strict';
const {TIMING,randomItem,emptyCells,healthBar,bindDirectionalInput,renderRunHistory}=RPGShared;
const N=4,BOSS_INTERVAL=20,MOVE_MS=TIMING.MOVE,MERGE_MS=TIMING.MERGE,DAMAGE_MS=TIMING.EFFECT,DEATH_MS=TIMING.DEATH;
const grid=document.getElementById('grid'),pieces=document.getElementById('pieces'),effects=document.getElementById('effects'),board=document.getElementById('board'),logEl=document.getElementById('log'),overlay=document.getElementById('overlay');
for(let i=0;i<16;i++){let d=document.createElement('div');d.className='cell';grid.appendChild(d)}
let E=[],turn=0,mergeCount=0,id=1,ended=false,bossLevel=1,bossDefeated=0,nextBossTurn=20,bossActive=false,busy=false,score=0,moveCount=0,enemyDefeated=0,heroesLost=0,highestTile=1,moveScore=0,mergeScore=0,enemyScore=0,bossScore=0,deathPenalty=0,warriorKills=0,archerKills=0,mageKills=0;
const wait=ms=>new Promise(r=>setTimeout(r,ms)),bossMax=()=>10+(bossLevel-1)*5,enemyDamage=()=>Math.ceil((bossDefeated+1)/2),bossDamage=()=>Math.ceil(bossLevel/2);
const BOSS_SET=[['⚔️','暗影劍士'],['🌑','暗夜領主'],['👁️','深淵之眼'],['☠️','死亡之影'],['👑','暗影之王']];
function roman(n){const map=[[10,'X'],[9,'IX'],[5,'V'],[4,'IV'],[1,'I']];let out='';for(const[v,r]of map)while(n>=v){out+=r;n-=v}return out}
function bossInfo(level=bossLevel){let i=(level-1)%BOSS_SET.length,cycle=Math.floor((level-1)/BOSS_SET.length)+1,[icon,name]=BOSS_SET[i];return{icon,name:name+(cycle>1?' '+roman(cycle):'')}}
function empty(){return emptyCells(E,N)}
function heroLimit(e){return Math.max(1,e.tier||1)}
function addHero(){let a=empty();if(!a.length)return false;let pos=randomItem(a),r=pos[0],c=pos[1];E.push({id:id++,type:'hero',tier:2,r,c,hits:0,dying:false});return true}
function addEnemy(isBoss=false){let a=empty();if(!a.length)return false;let pos=randomItem(a),r=pos[0],c=pos[1];E.push({id:id++,type:isBoss?'boss':'enemy',r,c,hits:0,maxHits:isBoss?bossMax():1,damage:isBoss?bossDamage():enemyDamage(),dying:false});return true}
function at(r,c,skip,list=E){return list.find(x=>x.id!==skip&&x.r===r&&x.c===c)}
function remaining(e){return Math.max(0,(e.type==='hero'?heroLimit(e):e.maxHits)-(e.hits||0))}
function heroValue(e){return Math.max(1,(e.tier||2)/2)}
function step(){return(pieces.clientWidth-24)/4+8}
function cls(e){return e.type==='hero'?'heroUnit':e.type==='boss'?'boss':'enemy'}
function inner(e){if(e.type==='hero')return '<div class="heroNum">'+heroValue(e)+'</div>'+healthBar(remaining(e),heroLimit(e),'hero');if(e.type==='boss'){let b=bossInfo();return '<div class="icon">'+b.icon+'</div><div class="name">'+b.name+'</div>'+healthBar(remaining(e),e.maxHits,'boss','ATK '+e.damage)}return '<div class="icon">🥷</div><div class="name">暗影刺客 Lv.'+(bossDefeated+1)+'</div><div class="unitMeta">ATK '+e.damage+'</div>'}
function render(){pieces.innerHTML='';let s=step();for(let e of E){let d=document.createElement('div');d.className='piece '+cls(e);d.dataset.id=e.id;d.style.transform='translate('+(e.c*s)+'px,'+(e.r*s)+'px)';d.innerHTML=inner(e);pieces.appendChild(d)}document.getElementById('score').textContent=score;document.getElementById('turn').textContent=turn;document.getElementById('merges').textContent=mergeCount;document.getElementById('wave').textContent=bossLevel;let b=E.find(x=>x.type==='boss'&&!x.dying);document.getElementById('boss').textContent=b?remaining(b)+' HP':Math.max(0,nextBossTurn-turn)}
function deathFx(e){let d=document.createElement('div'),s=step();d.className='deathfx '+cls(e);d.style.transform='translate('+(e.c*s)+'px,'+(e.r*s)+'px)';d.innerHTML=inner(e);effects.appendChild(d);setTimeout(()=>d.remove(),DEATH_MS)}
function mergeFx(e){if(!e||e.type!=='hero')return;let d=document.createElement('div'),s=step();d.className='mergefx';d.style.transform='translate('+(e.c*s)+'px,'+(e.r*s)+'px)';d.innerHTML=inner(e);effects.appendChild(d);setTimeout(()=>d.remove(),MERGE_MS)}
function damageFx(e,n){if(!e||!n)return;let d=document.createElement('div'),s=step();d.className='damagefx';d.style.transform='translate('+(e.c*s)+'px,'+(e.r*s)+'px)';d.textContent='-'+n+' HP';effects.appendChild(d);setTimeout(()=>d.remove(),DAMAGE_MS)}
function meleeFx(target){if(!target)return;let d=document.createElement('div'),s=step();d.className='meleeFx';d.style.transform='translate('+(target.c*s)+'px,'+(target.r*s)+'px)';effects.appendChild(d);setTimeout(()=>d.remove(),380)}
function arrowFx(source,target){if(!source||!target)return;let s=step(),cell=s-8,x1=source.c*s+cell/2,y1=source.r*s+cell/2,x2=target.c*s+cell/2,y2=target.r*s+cell/2,dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI,d=document.createElement('div');d.className='arrowFx';d.style.left=x1+'px';d.style.top=y1+'px';d.style.width=len+'px';d.style.transform='rotate('+ang+'deg)';effects.appendChild(d);setTimeout(()=>d.remove(),440)}
function mageFx(){let d=document.createElement('div');d.className='mageFx';effects.appendChild(d);setTimeout(()=>d.remove(),650)}
async function animateMoves(records){if(!records.length)return;let s=step();for(let m of records){let base=pieces.querySelector('[data-id="'+m.id+'"]');if(base)base.classList.add('hideForMove');let g=document.createElement('div');g.className='moveghost '+m.cls;g.innerHTML=m.html;g.style.transform='translate('+(m.fromC*s)+'px,'+(m.fromR*s)+'px)';effects.appendChild(g);m.el=g}requestAnimationFrame(()=>requestAnimationFrame(()=>{for(let m of records)m.el.style.transform='translate('+(m.toC*s)+'px,'+(m.toR*s)+'px)'}));await wait(MOVE_MS);for(let m of records)m.el.remove()}
function markHeroDamage(e,n){if(!e||e.type!=='hero'||e.dying)return 0;let dmg=Math.min(n,remaining(e));if(dmg<=0)return 0;damageFx(e,dmg);e.hits+=dmg;if(e.hits>=heroLimit(e))e.dying=true;return dmg}
function markEnemyDamage(e,n=1,source='warrior'){if(!e||e.type==='hero'||e.dying)return 0;let dmg=Math.min(n,remaining(e));if(dmg<=0)return 0;damageFx(e,dmg);e.hits+=dmg;if(e.hits>=e.maxHits){e.dying=true;e.killedBy=source}return dmg}
async function finishDeaths(){let dead=E.filter(x=>x.dying);if(!dead.length)return;for(let e of dead)deathFx(e);let bossDead=false;for(let e of dead){if(e.type==='hero'){heroesLost++;let loss=Math.min(score,heroValue(e));score-=loss;deathPenalty+=loss}else{enemyDefeated++;if(e.killedBy==='warrior')warriorKills++;else if(e.killedBy==='archer')archerKills++;else if(e.killedBy==='mage')mageKills++;if(e.type==='enemy'){score+=20;enemyScore+=20}else if(e.type==='boss'){bossDead=true;score+=100;bossScore+=100}}}E=E.filter(x=>!x.dying);if(bossDead){bossActive=false;bossDefeated++;bossLevel++;nextBossTurn=turn+BOSS_INTERVAL;logEl.textContent='Boss 擊敗！暗影刺客進入 Lv.'+(bossDefeated+1)+'：ATK '+enemyDamage()+'；下一隻 Boss 預計於第 '+nextBossTurn+' 回合登場。'}render();await wait(DEATH_MS)}
function makeMoveRecord(e,fr,fc,tr,tc){return{id:e.id,fromR:fr,fromC:fc,toR:tr,toC:tc,cls:cls(e),html:inner(e)}}
function planPlayer(dir){let list=JSON.parse(JSON.stringify(E)),before=JSON.stringify(list.map(x=>[x.id,x.r,x.c,x.tier,x.hits||0,x.dying?1:0])),hs=list.filter(x=>x.type==='hero'&&!x.dying),dr=dir==='up'?-1:dir==='down'?1:0,dc=dir==='left'?-1:dir==='right'?1:0;hs.sort((a,b)=>dir==='left'?a.c-b.c:dir==='right'?b.c-a.c:dir==='up'?a.r-b.r:b.r-a.r);let merged=new Set,mergeIds=[],moves=[],contacts=[];for(let h of hs){if(!list.some(x=>x.id===h.id))continue;let sr=h.r,sc=h.c;while(true){let nr=h.r+dr,nc=h.c+dc;if(nr<0||nr>=N||nc<0||nc>=N)break;let o=at(nr,nc,h.id,list);if(!o){h.r=nr;h.c=nc;continue}if(o.type==='hero'&&!o.dying&&o.tier===h.tier&&!merged.has(o.id)){let old=o.tier,ro=old-(o.hits||0),rh=h.tier-(h.hits||0),nt=old*2,rem=Math.min(nt,ro+rh);moves.push(makeMoveRecord(h,sr,sc,o.r,o.c));o.tier=nt;o.hits=nt-rem;list=list.filter(x=>x.id!==h.id);merged.add(o.id);mergeIds.push(o.id);break}if(o.type!=='hero'){contacts.push({heroId:h.id,enemyId:o.id});break}break}if(list.some(x=>x.id===h.id)&&(sr!==h.r||sc!==h.c))moves.push(makeMoveRecord(h,sr,sc,h.r,h.c))}let changed=contacts.length>0||before!==JSON.stringify(list.map(x=>[x.id,x.r,x.c,x.tier,x.hits||0,x.dying?1:0]));return{changed,list,moves,mergeIds,contacts}}
function canMove(){return['left','right','up','down'].some(d=>planPlayer(d).changed)}
function skillEventsForMerge(h){mergeCount++;let gained=heroValue(h);score+=gained;mergeScore+=gained;highestTile=Math.max(highestTile,gained);let events=[],f=['戰士'];for(let q of E.filter(x=>x.type!=='hero'&&!x.dying&&Math.abs(x.r-h.r)+Math.abs(x.c-h.c)===1))events.push({kind:'melee',source:h,target:q});if(mergeCount%3===0){let t=E.filter(x=>x.type!=='hero'&&!x.dying),q=randomItem(t);if(q){events.push({kind:'arrow',source:h,target:q});f.push('弓箭手')}}if(mergeCount%5===0){let t=E.filter(x=>x.type!=='hero'&&!x.dying);if(t.length){events.push({kind:'mage',source:h,targets:t});f.push('法師')}}logEl.textContent='第 '+mergeCount+' 次合成：'+f.join('、')+'能力觸發。';return events}
async function resolveAttackEvents(events){if(!events.length)return;let mageShown=false;for(let ev of events){if(ev.kind==='melee'){if(E.some(x=>x.id===ev.target.id)&&!ev.target.dying){meleeFx(ev.target);markEnemyDamage(ev.target,1,'warrior')}}else if(ev.kind==='arrow'){if(E.some(x=>x.id===ev.target.id)&&!ev.target.dying){arrowFx(ev.source,ev.target);markEnemyDamage(ev.target,1,'archer')}}else if(ev.kind==='mage'){if(!mageShown){mageFx();mageShown=true}for(let q of ev.targets)if(E.some(x=>x.id===q.id)&&!q.dying)markEnemyDamage(q,1,'mage')}else if(ev.kind==='contact'||ev.kind==='enemyAttack'){let h=E.find(x=>x.id===ev.heroId),en=E.find(x=>x.id===ev.enemyId);if(h&&en&&!h.dying&&!en.dying){meleeFx(h);markHeroDamage(h,en.damage||1)}}}render();await wait(DAMAGE_MS);await finishDeaths()}
function planEnemyPhase(){let moves=[],attacks=[];for(let e of E.filter(x=>x.type!=='hero'&&!x.dying)){let adj=E.find(h=>h.type==='hero'&&!h.dying&&Math.abs(h.r-e.r)+Math.abs(h.c-e.c)===1);if(adj){attacks.push({kind:'enemyAttack',enemyId:e.id,heroId:adj.id});continue}let hs=E.filter(x=>x.type==='hero'&&!x.dying);if(!hs.length)break;hs.sort((a,b)=>(Math.abs(a.r-e.r)+Math.abs(a.c-e.c))-(Math.abs(b.r-e.r)+Math.abs(b.c-e.c)));let h=hs[0],opts=[[Math.sign(h.r-e.r),0],[0,Math.sign(h.c-e.c)]],sr=e.r,sc=e.c;for(let[rr,cc]of opts){let nr=e.r+rr,nc=e.c+cc;if((rr||cc)&&nr>=0&&nr<N&&nc>=0&&nc<N&&!at(nr,nc,e.id)){e.r=nr;e.c=nc;moves.push(makeMoveRecord(e,sr,sc,nr,nc));break}}}return{moves,attacks}}
function end(t){if(ended)return;ended=true;let skillTotal=warriorKills+archerKills+mageKills,skills='<div class="skillCard"><h3>技能戰績</h3><div class="skills"><div class="skill">⚔️<b>'+warriorKills+'</b><span>戰士斬擊</span></div><div class="skill">🏹<b>'+archerKills+'</b><span>弓箭手</span></div><div class="skill">🔮<b>'+mageKills+'</b><span>法師魔法</span></div></div><div class="skillTotal">技能擊殺合計 '+skillTotal+' = 擊殺敵人 '+enemyDefeated+'</div></div>';document.getElementById('op').innerHTML=renderRunHistory({title:t,score,scoreRows:[{label:'移動得分',value:'+'+moveScore,className:'plus'},{label:'合併得分',value:'+'+mergeScore,className:'plus'},{label:'擊殺暗影刺客',value:'+'+enemyScore,className:'plus'},{label:'擊敗 Boss',value:'+'+bossScore,className:'plus'},{label:'英雄死亡',value:'−'+deathPenalty,className:'minus'}],historyRows:[{label:'存活回合',value:turn},{label:'移動次數',value:moveCount},{label:'合併次數',value:mergeCount},{label:'擊殺敵人',value:enemyDefeated},{label:'其中 Boss',value:bossDefeated},{label:'英雄死亡',value:heroesLost},{label:'最高英雄數字',value:highestTile}],skillsHtml:skills,backHtml:'<a href="../type-01/">回到首頁</a>'});overlay.classList.add('show');document.getElementById('again').onclick=reset}
function check(){if(!E.some(x=>x.type==='hero'&&!x.dying))return end('隊伍全滅');if(!canMove())return end('無法移動')}
async function move(d){if(ended||busy)return;let plan=planPlayer(d);if(!plan.changed){check();render();return}busy=true;moveCount++;score++;moveScore++;render();await animateMoves(plan.moves);E=plan.list;render();if(plan.mergeIds.length){for(let mid of plan.mergeIds){let h=E.find(x=>x.id===mid);if(h)mergeFx(h)}await wait(MERGE_MS)}let attacks=[];for(let mid of plan.mergeIds){let h=E.find(x=>x.id===mid);if(h)attacks.push(...skillEventsForMerge(h))}for(let c of plan.contacts)attacks.push({kind:'contact',heroId:c.heroId,enemyId:c.enemyId});await resolveAttackEvents(attacks);if(!E.some(x=>x.type==='hero'&&!x.dying)){check();busy=false;return}turn++;render();let ep=planEnemyPhase();if(ep.moves.length){render();await animateMoves(ep.moves);render()}await resolveAttackEvents(ep.attacks);if(!E.some(x=>x.type==='hero'&&!x.dying)){check();busy=false;return}if(turn%2===0)addEnemy(false);addHero();if(turn>=nextBossTurn&&!bossActive){if(addEnemy(true)){bossActive=true;let b=bossInfo();logEl.textContent+=' '+b.icon+' '+b.name+' 登場！擁有 '+bossMax()+' HP / ATK '+bossDamage()+'。'}}render();check();busy=false}
function reset(){E=[];turn=0;mergeCount=0;id=1;ended=false;bossLevel=1;bossDefeated=0;nextBossTurn=20;bossActive=false;busy=false;score=0;moveCount=0;enemyDefeated=0;heroesLost=0;highestTile=1;moveScore=0;mergeScore=0;enemyScore=0;bossScore=0;deathPenalty=0;warriorKills=0;archerKills=0;mageKills=0;effects.innerHTML='';overlay.classList.remove('show');addHero();addHero();addHero();logEl.textContent='v1.0 正式版：第一隻 Boss 將在第 20 回合登場。';render()}
bindDirectionalInput({board,onMove:move,threshold:25,keyMap:{ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}});document.getElementById('restart').onclick=reset;window.addEventListener('resize',render);reset();
window.__V1_TEST__={roman,bossInfo,heroValue,remaining,planPlayer};
})();