(function(){'use strict';
const {arraysEqual,bindDirectionalInput,randomItem}=RPGShared;const N=4,GOAL=1024;
const gridEl=document.getElementById('grid'),tilesEl=document.getElementById('tiles'),boardEl=document.getElementById('board'),scoreEl=document.getElementById('score'),bestEl=document.getElementById('best'),overlay=document.getElementById('overlay'),overlayTitle=document.getElementById('overlayTitle'),overlayText=document.getElementById('overlayText'),continueBtn=document.getElementById('continueBtn');
for(let i=0;i<16;i++){const d=document.createElement('div');d.className='cell';gridEl.appendChild(d)}
let board=Array.from({length:N},()=>Array(N).fill(0)),score=0,best=Number(localStorage.getItem('best1024')||0),locked=false,won=false;bestEl.textContent=best;
function addRandom(){const e=[];for(let r=0;r<N;r++)for(let c=0;c<N;c++)if(board[r][c]===0)e.push([r,c]);const pos=randomItem(e);if(!pos)return;const[r,c]=pos;board[r][c]=Math.random()<.9?2:4}
function tileClass(v){return v>=2048?'vbig':'v'+v}
function render(spawnKeys=[],mergeKeys=[]){tilesEl.innerHTML='';const w=tilesEl.clientWidth,gap=window.innerWidth<=380?9:12,size=(w-gap*3)/4;for(let r=0;r<N;r++)for(let c=0;c<N;c++){const v=board[r][c];if(!v)continue;const d=document.createElement('div'),key=r+','+c;d.className='tile '+tileClass(v)+(spawnKeys.includes(key)?' spawn':'')+(mergeKeys.includes(key)?' merge':'');d.textContent=v;d.style.width=size+'px';d.style.height=size+'px';d.style.transform='translate('+(c*(size+gap))+'px,'+(r*(size+gap))+'px)';tilesEl.appendChild(d)}scoreEl.textContent=score;if(score>best){best=score;bestEl.textContent=best;localStorage.setItem('best1024',String(best))}}
function reset(){board=Array.from({length:N},()=>Array(N).fill(0));score=0;locked=false;won=false;overlay.classList.remove('show');addRandom();addRandom();requestAnimationFrame(()=>render())}
function compress(line){const vals=line.filter(v=>v!==0),out=[],merged=[];let gain=0;for(let i=0;i<vals.length;i++){if(vals[i]===vals[i+1]){out.push(vals[i]*2);gain+=vals[i]*2;merged.push(out.length-1);i++}else out.push(vals[i])}while(out.length<N)out.push(0);return{line:out,gain,merged}}
function move(dir){if(locked||overlay.classList.contains('show'))return;const old=board.map(r=>r.slice());let gained=0,mergeKeys=[];if(dir==='left'||dir==='right'){for(let r=0;r<N;r++){let line=board[r].slice();if(dir==='right')line.reverse();const res=compress(line);gained+=res.gain;let nl=res.line;if(dir==='right')nl=nl.slice().reverse();board[r]=nl;for(const idx of res.merged){const c=dir==='right'?N-1-idx:idx;mergeKeys.push(r+','+c)}}}else{for(let c=0;c<N;c++){let line=[];for(let r=0;r<N;r++)line.push(board[r][c]);if(dir==='down')line.reverse();const res=compress(line);gained+=res.gain;let nl=res.line;if(dir==='down')nl=nl.slice().reverse();for(let r=0;r<N;r++)board[r][c]=nl[r];for(const idx of res.merged){const r=dir==='down'?N-1-idx:idx;mergeKeys.push(r+','+c)}}}let changed=false;for(let r=0;r<N;r++)if(!arraysEqual(old[r],board[r])){changed=true;break}if(!changed)return;locked=true;score+=gained;render([],mergeKeys);setTimeout(()=>{const before=board.map(r=>r.slice());addRandom();let spawn=[];for(let r=0;r<N;r++)for(let c=0;c<N;c++)if(before[r][c]===0&&board[r][c]!==0)spawn.push(r+','+c);render(spawn,[]);locked=false;checkState()},155)}
function hasMoves(){for(let r=0;r<N;r++)for(let c=0;c<N;c++){if(board[r][c]===0)return true;if(c<N-1&&board[r][c]===board[r][c+1])return true;if(r<N-1&&board[r][c]===board[r+1][c])return true}return false}
function checkState(){if(!won&&board.some(row=>row.some(v=>v>=GOAL))){won=true;overlayTitle.textContent='你合成 1024 了！';overlayText.textContent='目前分數：'+score.toLocaleString();continueBtn.style.display='inline-block';overlay.classList.add('show');return}if(!hasMoves()){overlayTitle.textContent='遊戲結束';overlayText.textContent='最終分數：'+score.toLocaleString();continueBtn.style.display='none';overlay.classList.add('show')}}
bindDirectionalInput({board:boardEl,onMove:move,threshold:24});document.getElementById('newGame').onclick=reset;document.getElementById('restartBtn').onclick=reset;continueBtn.onclick=()=>overlay.classList.remove('show');window.addEventListener('resize',()=>render());reset();
window.__CLASSIC_TEST__={compress,hasMoves,getBoard:()=>board.map(r=>r.slice()),setBoard:b=>{board=b.map(r=>r.slice())}};
})();