(function(){'use strict';
const ICONS={crowd:'👥',killingIntent:'😈',warSweep:'🪃',warImpact:'💫',rangerSnipe:'🔭',priestPunish:'⚖️',ascend:'⏫',encore:'🎼',awakening:'🌅'};
const BASIC={
warrior:{entryName:'迎戰',entry:'特殊戰士進場時，隨機攻擊周圍 8 格內最多 2 名敵人，各造成 1 技能傷害。',moveName:'突進',move:'戰士實際移動後若被前方敵人阻擋，對該敵人造成 1 技能傷害。'},
ranger:{entryName:'遠射',entry:'特殊遊俠進場時，隨機攻擊周圍 8 格以外最多 2 名敵人，各造成 1 技能傷害。',moveName:'回身射擊',move:'遊俠實際移動後，向移動反方向射擊，命中直線上最近的敵人並造成 1 技能傷害。'},
priest:{entryName:'治癒波',entry:'特殊祭司進場時，使周圍 8 格內受傷的友方各恢復 1 HP。',moveName:'守護',move:'祭司實際移動後，自己與周圍 8 格內友方獲得 1 次完全抵銷傷害的守護；再次施放會刷新，不疊加。'}
};
function patchSkillIcons(){const api=window.__V2_TEST__;if(!api)return;for(const s of api.getSkills())if(ICONS[s.id]&&s.icon!==ICONS[s.id])s.icon=ICONS[s.id];const pools=api.getClassSkills();for(const s of [...Object.values(pools.CLASS_SKILLS).flat(),...pools.COMMON_SKILLS])if(ICONS[s.id]&&s.icon!==ICONS[s.id])s.icon=ICONS[s.id];const prof=api.getProfessions();if(prof){if(prof.warrior.icon!=='⚔️')prof.warrior.icon='⚔️';if(prof.ranger.icon!=='🏹')prof.ranger.icon='🏹';if(prof.priest.icon!=='✝️')prof.priest.icon='✝️'}}
function basicHtml(id){const b=BASIC[id];if(!b)return'';return '<div class="professionBasics"><div class="basicSkill"><span class="basicLabel">基本技能 1</span><strong>'+b.entryName+'</strong><p>'+b.entry+'</p></div><div class="basicSkill"><span class="basicLabel">基本技能 2</span><strong>'+b.moveName+'</strong><p>'+b.move+'</p></div></div>'}
function patchProfessionChoices(){const title=document.querySelector('#panel h2');if(!title||title.textContent.trim()!=='選擇特殊職業')return;document.querySelectorAll('#panel .choice[data-id]').forEach(btn=>{const id=btn.dataset.id,b=BASIC[id];if(!b||btn.dataset.basicPatched)return;const span=btn.querySelector('span:last-child');if(span){const p=window.__V2_TEST__&&window.__V2_TEST__.getProfessions()[id];span.innerHTML='<span class="professionDesc">'+(p?p.desc:'')+'</span>'+basicHtml(id);btn.dataset.basicPatched='1'}})}
function currentProfession(){const api=window.__V2_TEST__;if(!api)return null;const box=document.getElementById('profession');if(!box)return null;const txt=box.textContent||'';const profs=api.getProfessions();return Object.values(profs).find(p=>txt.includes(p.name))||null}
function showProfessionDetail(){const p=currentProfession();if(!p)return;const b=BASIC[p.id];if(!b)return;const modal=document.getElementById('modal'),panel=document.getElementById('panel');if(!modal||!panel)return;panel.innerHTML='<div class="detail professionDetail"><div class="big">'+p.icon+'</div><h2>'+p.name+'</h2><p class="professionDetailDesc">'+p.desc+'</p>'+basicHtml(p.id)+'<button class="close">關閉</button></div>';modal.classList.add('show');panel.querySelector('.close').onclick=()=>modal.classList.remove('show')}
function bindProfessionBox(){const box=document.querySelector('.professionBox');if(!box||box.dataset.detailBound)return;box.dataset.detailBound='1';box.setAttribute('role','button');box.setAttribute('tabindex','0');box.title='查看特殊職業基本技能';box.addEventListener('click',showProfessionDetail);box.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showProfessionDetail()}})}
function patchVisibleLabels(){document.querySelectorAll('.animSkillTag').forEach(el=>{const old=el.textContent;const next=old.replace(/^👑 覺醒/,'🌅 覺醒').replace(/^🌟 躍升/,'⏫ 躍升').replace(/^🎯 狙擊/,'🔭 狙擊').replace(/^🗡️ 橫掃/,'🪃 橫掃').replace(/^💢 衝擊/,'💫 衝擊').replace(/^✨ 懲戒/,'⚖️ 懲戒').replace(/^🔁 連奏/,'🎼 連奏').replace(/^🧱 人海/,'👥 人海').replace(/^🔴 殺意/,'😈 殺意');if(next!==old)el.textContent=next})}
function patchAll(){patchSkillIcons();patchVisibleLabels();patchProfessionChoices();bindProfessionBox()}
patchAll();
let scheduled=false;
new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;patchAll()})}).observe(document.body,{childList:true,subtree:true});
window.__V04_VISUAL__={icons:ICONS,basic:BASIC};
})();