(()=>{'use strict';
class V07PriestClassSkills{
 constructor(runtime,random=Math.random){this.r=runtime;this.random=random;this.bind()}
 has(id){return this.r.state.hasClassSkill(id)}
 level(id){return this.r.mastery.level(id)}
 priests(){return this.r.state.living('hero').filter(h=>h.special&&h.profession==='priest')}
 bind(){this.r.events.on('SPECIAL_ENTRY',e=>this.onEntry(e));this.r.events.on('REVIVAL_CHECK',e=>this.onRevivalCheck(e));this.r.events.on('DEATH_CANCELLED',e=>this.onRevived(e));this.r.events.on('GUARD_BLOCK',e=>this.onGuardBlock(e));return this}
 async onEntry(e){const p=e.hero;if(!p||p.profession!=='priest')return;const level=this.has('priestHolyHeal')?this.level('priestHolyHeal'):0,amount=level?[1,2,3,3][level-1]:1,targets=level?this.r.state.living('hero'):V07CombatTargeting.around8(p,this.r.state.living('hero'));for(const h of targets)this.r.units.heal(h,amount);if(level===4)for(const h of targets)h.guard=true;await this.r.events.emit('PRIEST_HEAL',{priest:p,targets,amount,reason:e.reason})}
 async onRevivalCheck(e){if(!this.has('priestRevive')||e.unit?.type!=='hero'||e.unit.revived)return;const priest=this.priests().find(p=>V07CombatTargeting.around8(p,[e.unit]).length);if(!priest)return;const level=this.level('priestRevive');e.revive=true;e.hp=[1,2,3,3][level-1];e.priest=priest}
 async onRevived(e){const hero=e.unit;if(!hero?.revived||!this.has('priestRevive')||this.level('priestRevive')!==4)return;const priest=this.priests().find(p=>V07CombatTargeting.around8(p,[hero]).length);if(!priest)return;const nearby=V07CombatTargeting.around8(priest,V07CombatTargeting.enemies(this.r.state)).filter(x=>x.type==='enemy');for(const enemy of nearby){const cell={r:enemy.r,c:enemy.c};enemy.dead=true;this.r.board.compactDead();this.r.board.add({type:'hero',tier:16,r:cell.r,c:cell.c,hits:0,special:false,profession:null,guard:false,revived:false,reincarnated:false,reincarnateEligible:false})}if(nearby.length)await this.r.events.emit('PRIEST_REVIVE_CONVERT',{priest,hero,count:nearby.length})}
 sideTargets(hero,source){if(!source)return[];const dr=Math.sign(source.r-hero.r),dc=Math.sign(source.c-hero.c),all=V07CombatTargeting.enemies(this.r.state);if(Math.abs(dr)>=Math.abs(dc)){const row=hero.r+dr;return all.filter(x=>x.r===row&&Math.abs(x.c-hero.c)<=1)}const col=hero.c+dc;return all.filter(x=>x.c===col&&Math.abs(x.r-hero.r)<=1)}
 async onGuardBlock(e){if(!this.has('priestPunish'))return;const level=this.level('priestPunish'),hero=e.hero,source=e.source;if(level===2&&this.random()<.20)hero.guard=true;let targets=[];if(level<=2){if(source&&V07CombatTargeting.enemies(this.r.state).some(x=>x.id===source.id))targets=[source]}else if(level===3)targets=this.sideTargets(hero,source);else targets=V07CombatTargeting.around8(hero,V07CombatTargeting.enemies(this.r.state));const seen=new Set();for(const t of targets){if(seen.has(t.id))continue;seen.add(t.id);await this.r.damage.apply(t,1,{source:hero,kind:'priest-punish'})}await this.r.deaths.settle()}
}
window.V07PriestClassSkills=V07PriestClassSkills;
})();