(function(root,factory){const api=factory(root.RPGShared);if(typeof module==='object'&&module.exports)module.exports=api;root.RPGAnimations=api})(typeof globalThis!=='undefined'?globalThis:this,function(shared){'use strict';
const FALLBACK={EFFECT:750,SLASH:360};
const TIMING=(shared&&shared.TIMING)||FALLBACK;
const BUILTIN_TYPES=Object.freeze(['damage','heal','buff','slash','burst','arrow','magic-wave','board-wave','skill-tag','pulse']);
function createAnimator(opts={}){const effects=opts.effects,step=opts.step;if(!effects)throw new Error('RPGAnimations requires an effects element');if(typeof step!=='function')throw new Error('RPGAnimations requires a step() function');const registry=new Map();
function tileAnchor(target,className='animTileAnchor'){if(!target)return null;const s=step(),el=document.createElement('div');el.className=className;el.style.transform='translate('+(target.c*s)+'px,'+(target.r*s)+'px)';effects.appendChild(el);return el}
function removeLater(el,duration){setTimeout(()=>el&&el.remove(),duration)}
function tileText(target,text,kind,duration){const anchor=tileAnchor(target);if(!anchor)return null;const inner=document.createElement('div');inner.className='animTileText '+kind;inner.textContent=text;anchor.appendChild(inner);removeLater(anchor,duration);return anchor}
function register(name,handler){if(typeof handler!=='function')throw new Error('Animation handler must be a function');registry.set(name,handler);return api}
function play(name,payload={}){const handler=registry.get(name);if(!handler)throw new Error('Unknown animation: '+name);return handler(payload)}
const api={play,register,types:()=>Array.from(registry.keys())};
register('damage',p=>tileText(p.target,'-'+p.value+' HP','animDamage',p.duration||TIMING.EFFECT));
register('heal',p=>tileText(p.target,'+'+p.value+' HP','animHeal',p.duration||TIMING.EFFECT));
register('buff',p=>tileText(p.target,p.text,'animBuff',p.duration||TIMING.EFFECT));
register('slash',p=>{const anchor=tileAnchor(p.target);if(!anchor)return null;const stroke=document.createElement('div');stroke.className='animSlashStroke';anchor.appendChild(stroke);removeLater(anchor,p.duration||Math.max(400,TIMING.SLASH));return anchor});
register('burst',p=>{const anchor=tileAnchor(p.target);if(!anchor)return null;const icon=document.createElement('div');icon.className='animBurstIcon';icon.textContent=p.icon||'✨';const dx=(p.target.c<1.5?-1:1)*(58+Math.abs(p.target.r-1.5)*10),dy=(p.target.r<1.5?-1:1)*(42+Math.abs(p.target.c-1.5)*8);icon.style.setProperty('--from-x',dx+'px');icon.style.setProperty('--from-y',dy+'px');const ring=document.createElement('div');ring.className='animImpactRing';anchor.appendChild(icon);anchor.appendChild(ring);removeLater(anchor,p.duration||TIMING.EFFECT);return anchor});
register('arrow',p=>{if(!p.source||!p.target)return null;const s=step(),cell=s-8,x1=p.source.c*s+cell/2,y1=p.source.r*s+cell/2,x2=p.target.c*s+cell/2,y2=p.target.r*s+cell/2,dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI,duration=p.duration||440,el=document.createElement('div');el.className='animArrow';el.style.left=x1+'px';el.style.top=y1+'px';el.style.width=len+'px';el.style.transform='rotate('+ang+'deg)';const line=document.createElement('div');line.className='animArrowLine';const head=document.createElement('div');head.className='animArrowHead';head.textContent='➤';el.appendChild(line);el.appendChild(head);effects.appendChild(el);if(head.animate)head.animate([{transform:'translateX(0)',opacity:0},{transform:'translateX('+(len*.15)+'px)',opacity:1,offset:.15},{transform:'translateX('+len+'px)',opacity:1,offset:.82},{transform:'translateX('+len+'px)',opacity:0}],{duration,easing:'ease-out',fill:'forwards'});removeLater(el,duration);return el});
register('magic-wave',p=>{const el=document.createElement('div');el.className='animMagicWave';el.innerHTML='<div class="animMagicGlow"></div><div class="animMagicRing ring1"></div><div class="animMagicRing ring2"></div>';effects.appendChild(el);removeLater(el,p.duration||650);return el});
register('board-wave',p=>{const el=document.createElement('div');el.className='animBoardWave';el.innerHTML='<div class="animBoardGlow"></div>';effects.appendChild(el);removeLater(el,p.duration||TIMING.EFFECT);return el});
register('skill-tag',p=>{const el=document.createElement('div');el.className='animSkillTag';el.textContent=p.text||'';effects.appendChild(el);removeLater(el,p.duration||TIMING.EFFECT);return el});
register('pulse',p=>{const el=p.element;if(!el)return null;el.classList.remove('animPulse');void el.offsetWidth;el.classList.add('animPulse');return el});
return api}
return{BUILTIN_TYPES,createAnimator};
});