(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.RPGShared=api})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const TIMING=Object.freeze({MOVE:250,MERGE:250,EFFECT:750,DEATH:250,SPAWN:450,SLASH:360});
const DIR_KEYS=Object.freeze({ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down',a:'left',d:'right',w:'up',s:'down'});
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function randomItem(a,rng=Math.random){return a&&a.length?a[Math.floor(rng()*a.length)]:null}
function arraysEqual(a,b){return Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&a.every((v,i)=>v===b[i])}
function emptyCells(entities,n=4){const used=new Set((entities||[]).map(e=>e.r+','+e.c)),out=[];for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(!used.has(r+','+c))out.push([r,c]);return out}
function hpPercent(current,max){return max>0?clamp(current/max*100,0,100):0}
function healthBar(current,max,kind='hero',meta=''){const pct=hpPercent(current,max);return '<div class="unitMeta">'+(meta||'')+'</div><div class="hpWrap"><div class="hpTrack"><div class="hpFill '+(kind==='boss'?'bossHp':'heroHp')+'" style="width:'+pct+'%"></div></div><div class="hpText">'+Math.max(0,current)+' / '+Math.max(0,max)+' HP</div></div>'}
function bindDirectionalInput(opts){const board=opts.board,onMove=opts.onMove,threshold=opts.threshold??24,keyMap=opts.keyMap||DIR_KEYS;let touch=null;const key=e=>{const k=typeof e.key==='string'?e.key:'';const dir=keyMap[k]||keyMap[k.toLowerCase()];if(dir){e.preventDefault();onMove(dir)}};const start=e=>{const t=e.changedTouches&&e.changedTouches[0];if(t)touch={x:t.clientX,y:t.clientY}};const end=e=>{if(!touch)return;const t=e.changedTouches&&e.changedTouches[0];if(!t){touch=null;return}const dx=t.clientX-touch.x,dy=t.clientY-touch.y;touch=null;if(Math.max(Math.abs(dx),Math.abs(dy))<threshold)return;onMove(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'))};window.addEventListener('keydown',key,{passive:false});board.addEventListener('touchstart',start,{passive:true});board.addEventListener('touchend',end,{passive:true});return()=>{window.removeEventListener('keydown',key);board.removeEventListener('touchstart',start);board.removeEventListener('touchend',end)}}
function resultRows(rows){return rows.map(r=>'<div class="resultRow"><span>'+r.label+'</span><b class="'+(r.className||'')+'">'+r.value+'</b></div>').join('')}
function renderRunHistory(cfg){const skills=cfg.skillsHtml||'';return '<div class="result"><div class="resultTitle">'+cfg.title+'</div><div class="scoreBox"><div class="scoreLabel">總分</div><span class="score">'+Number(cfg.score||0).toLocaleString()+'</span></div><div class="resultGrid"><div class="resultCard"><h3>得分明細</h3>'+resultRows(cfg.scoreRows||[])+'</div><div class="resultCard"><h3>遊戲歷程</h3>'+resultRows(cfg.historyRows||[])+'</div></div>'+skills+'<div class="resultActions">'+(cfg.backHtml||'')+'<button id="again">再玩一次</button></div></div>'}
return{TIMING,DIR_KEYS,clamp,randomItem,arraysEqual,emptyCells,hpPercent,healthBar,bindDirectionalInput,resultRows,renderRunHistory};
});