(function(){'use strict';
const {TIMING,randomItem,emptyCells,healthBar,bindDirectionalInput,renderRunHistory}=RPGShared;
const N=4,BI=20,MM=TIMING.MOVE,GM=TIMING.MERGE,FX=TIMING.EFFECT,DM=TIMING.DEATH;
const $=id=>document.getElementById(id),grid=$('grid'),pieces=$('pieces'),effects=$('effects'),board=$('board'),modal=$('modal'),panel=$('panel'),icons=$('skillIcons');
for(let i=0;i<N*N;i++){let d=document.createElement('div');d.className='cell';grid.appendChild(d)}
const S=[
['swift','👟','疾行','每 5 次有效移動，下一次有效移動不生成敵人。'],['wind','🌪️','風壓','一次滑動移動至少 4 名英雄時，隨機 1 名敵人受到 1 傷害。'],['momentum','⏳','餘勢','連續 3 回合沒有合併，第 3 回合所有英雄恢復 1 HP。'],['resonance','💥','共鳴','每 5 次合併，所有敵人受到 1 傷害。'],['overload','🔥','超載','同一次滑動發生 2 次以上合併，所有敵人受到 1 傷害。'],['luck','🍀','幸運','每累積 10 次有效移動，下一個普通英雄生成時有 25% 機率提升一階。'],['deathBlast','💣','遺爆','英雄死亡時，對周圍 8 格內隨機 1 名敵人造成 1 傷害。'],['legacy','👻','遺志','英雄死亡後，下一次合併額外攻擊 1 名隨機敵人。'],['blood','🩸','血祭','每 3 名我方單位死亡，下一次我方單位生成的等級提升一階（不累計）。'],['firstStrike','⚡','先制','Boss 出現時立即受到 2 傷害。'],['reinforce','🥇','優質增援','每生成 10 名英雄，第 10 名直接以數字 2 出現。'],['mutation','🎲','突變','新英雄有 10% 機率直接變成特殊單位。'],['risk','💎','高風險投資','敵人擊殺分數 ×2，但英雄死亡扣分也 ×2。'],['assault','💪','強襲','對 Boss 造成傷害時，傷害 +1。'],['precision','📐','精準','每 15 次合併，隨機 3 名敵人各受到 1 傷害。'],['backup','🪖','援軍','每次生成英雄時，有 5% 機率一次生成 2 名英雄。']
].map(x=>({id:x[0],icon:x[1],name:x[2],desc:x[3],kind:'general'}));
const PROFESSIONS={
warrior:{id:'warrior',icon:'⚔️',name:'戰士',desc:'近距離接敵與格位壓迫。',entry:'迎戰',move:'突進'},
ranger:{id:'ranger',icon:'🏹',name:'遊俠',desc:'保持距離、回身射擊與遠距壓制。',entry:'遠射',move:'回身射擊'},
priest:{id:'priest',icon:'✨',name:'祭司',desc:'治療、守護、復甦與反擊。',entry:'治癒波',move:'守護'}
};
const CLASS_SKILLS={
warrior:[
{id:'warSweep',icon:'🗡️',name:'橫掃',desc:'LV1 隨機 1 個有效方向；LV2 2 個；LV3 3 個；MAX 攻擊周圍 8 格全部敵人。每個方向涵蓋該側 3 格，重疊敵人只受 1 次傷害。'},
{id:'warImpact',icon:'💢',name:'衝擊',desc:'移動至少 2 格後，LV1/LV2/LV3/MAX 分別隨機攻擊周圍 8 格最多 1/2/3/4 名不同敵人，各 1 傷害。'},
{id:'warSmash',icon:'🔨',name:'重擊',desc:'合併後：LV1 攻擊相鄰十字 4 格；LV2 十字延伸至棋盤邊界；LV3 再加相鄰 4 個斜角；MAX 全場敵人各受 1 傷害。'}
],
ranger:[
{id:'rangerSnipe',icon:'🎯',name:'狙擊',desc:'遠射觸發時，LV1/LV2/LV3 攻擊符合遠射距離條件的最遠 2/3/4 名敵人；MAX 解除距離限制，改為全場隨機最多 3 名。'},
{id:'rangerQuickShot',icon:'🪶',name:'迅捷射擊',desc:'LV1/LV2/LV3：移動至少 2 格時額外觸發 1/2/3 次遠射；MAX 保留 3 次並取消至少移動 2 格限制。'},
{id:'rangerRain',icon:'🌧️',name:'箭雨',desc:'合併後，LV1/LV2/LV3 從周圍 8 格以外隨機攻擊最多 2/3/4 名敵人；MAX 全場所有敵人各受 1 傷害。'}
],
priest:[
{id:'priestHolyHeal',icon:'🌿',name:'聖療',desc:'治癒波改為全場治療：LV1 +1 HP、LV2 +2、LV3 +3；MAX +3 HP 並讓全場友方獲得 1 層守護。'},
{id:'priestRevive',icon:'🕊️',name:'復甦',desc:'祭司周圍 8 格內友方死亡時，LV1/LV2/LV3/MAX 分別以 1/2/3/3 HP 原地復活一次；MAX 額外將周圍 8 格內死亡的敵方單位轉為數字 8、HP 3 的普通我方英雄。'},
{id:'priestPunish',icon:'🔆',name:'懲戒',desc:'守護成功減傷時：LV1 反擊攻擊者 1；LV2 額外有 20% 機率不消耗守護；LV3 依攻擊方向對該側 3 格敵人各造成 1；MAX 改為被攻擊單位周圍 8 格爆炸傷害。'}
]
};
const COMMON_SKILLS=[{id:'ascend',icon:'🌟',name:'躍升',desc:'兩個特殊單位彼此合併時，合併結果一次提升 2 個數字階級。'},{id:'encore',icon:'🔁',name:'連奏',desc:'特殊單位的進場基礎能力自動額外施放 1 次。'},{id:'linkage',icon:'🔗',name:'連攜',desc:'新的特殊單位進場時，場上其他特殊單位各觸發 1 次自己的進場基礎能力。'},{id:'awakening',icon:'👑',name:'覺醒',desc:'當場上所有我方單位都只剩特殊單位時，本局之後生成的英雄全部直接成為特殊單位。'},{id:'reincarnate',icon:'♻️',name:'轉生',desc:'特殊單位第一次死亡時，下一個普通英雄改為特殊單位；由轉生產生的特殊單位不再具有轉生資格。'}];
const ALL_CLASS_SKILLS=[...Object.values(CLASS_SKILLS).flat(),...COMMON_SKILLS].map(s=>({...s,kind:'class'}));
let E=[],turn=0,merges=0,id=1,ended=false,busy=false,score=0,moves=0,best=1,bl=1,bd=0,next=20,bactive=false,spawn=0,noMerge=0,legacy=false,sel=[],classSel=[],profession=null,classChosen=false,nextSpecial=false,awakened=false,reincarnateQueue=0,claimedScoreMilestone=0,specialMilestoneQueue=0,moveScore=0,mergeScore=0,enemyScore=0,bossScore=0,deathPenalty=0,heroesLost=0,enemyDefeated=0,deathCount=0,bloodReady=false,skipEnemy=false,luckReady=false;
const wait=n=>new Promise(r=>setTimeout(r,n)),has=x=>sel.includes(x),hasClass=x=>classSel.includes(x),bmax=()=>10+(bl-1)*5,edmg=()=>Math.ceil((bd+1)/2),bdmg=()=>Math.ceil(bl/2),hv=e=>(e.tier||2)/2,max=e=>e.type==='hero'?e.tier:e.maxHits,rem=e=>Math.max(0,max(e)-(e.hits||0));
function empty(){return emptyCells(E,N)}function at(r,c,skip,list=E){return list.find(x=>x.id!==skip&&x.r===r&&x.c===c)}function step(){return(pieces.clientWidth-24)/4+8}function cls(e){if(e.type==='hero')return 'heroUnit'+(e.special?' specialUnit role-'+e.profession:'');return e.type==='boss'?'boss':'enemy'}
const anim=RPGAnimations.createAnimator({effects,step});
function inner(e){if(e.type==='hero'){let badge=e.special?'<div class="classBadge">'+PROFESSIONS[e.profession].icon+'</div>':'';let guard=e.guard?'<div class="guardBadge">🛡️</div>':'';return badge+guard+'<div class="heroNum">'+hv(e)+'</div>'+healthBar(rem(e),e.tier,'hero')}if(e.type==='boss')return '<div class="icon">👑</div><div class="name">Boss</div>'+healthBar(rem(e),e.maxHits,'boss','ATK '+e.damage);return '<div class="icon">🥷</div><div class="name">暗影刺客</div><div class="unitMeta">ATK '+e.damage+'</div>'}
function generalSkill(id){return S.find(x=>x.id===id)}function classSkill(id){return ALL_CLASS_SKILLS.find(x=>x.id===id)}function skillById(id){return generalSkill(id)||classSkill(id)}function currentClassPool(){return profession?[...CLASS_SKILLS[profession],...COMMON_SKILLS]:[]}function specialHeroes(){return E.filter(x=>x.type==='hero'&&x.special&&rem(x)>0)}function livingHeroes(){return E.filter(x=>x.type==='hero'&&rem(x)>0)}function livingEnemies(){return E.filter(x=>x.type!=='hero'&&rem(x)>0)}function near8(a,b){return Math.abs(a.r-b.r)<=1&&Math.abs(a.c-b.c)<=1&&(a.r!==b.r||a.c!==b.c)}
function rank(id){return RPGSave.rankFromUses(RPGSave.uses(id))}function rankLevel(id){let r=rank(id);return r==='MAX'?4:Number(String(r).replace('LV',''))||1}function useSkill(id,n=1){if(skillById(id))RPGSave.recordSkillUse(id,n)}
function maybeAwaken(){if(!profession||awakened||!hasClass('awakening'))return false;let hs=livingHeroes();if(hs.length&&hs.every(h=>h.special)){awakened=true;trig('awakening','👑 覺醒');return true}return false}
function scoreSpecialReady(){if(!profession)return false;let m=Math.floor(score/100)*100;if(m>claimedScoreMilestone){specialMilestoneQueue+=(m-claimedScoreMilestone)/100;claimedScoreMilestone=m}if(specialMilestoneQueue>0){specialMilestoneQueue--;return true}return false}
function shouldSpawnSpecial(){if(!profession)return false;if(awakened)return true;if(nextSpecial){nextSpecial=false;return true}if(scoreSpecialReady())return true;if(has('mutation')&&Math.random()<.10){useSkill('mutation');return true}if(reincarnateQueue>0){reincarnateQueue--;return true}return false}
function makeHero(tier=2,forcedSpecial=null,reincarnated=false){let a=empty();if(!a.length)return null;spawn++;let skill=null;if(has('reinforce')&&spawn%10===0){tier=4;skill='reinforce'}if(bloodReady){tier*=2;bloodReady=false;deathCount=0;skill='blood'}else if(luckReady){luckReady=false;if(Math.random()<.25){tier*=2;skill='luck'}}let special=forcedSpecial===null?shouldSpawnSpecial():forcedSpecial,p=randomItem(a),h={id:id++,type:'hero',tier,r:p[0],c:p[1],hits:0,special:!!special,profession:special?profession:null,revived:false,guard:false,guardBy:null,reincarnateEligible:!!special&&!reincarnated};E.push(h);return{e:h,skill}}
function addHero(){let first=makeHero();if(!first)return[];let out=[first];if(has('backup')&&empty().length&&Math.random()<.05){let second=makeHero(first.e.tier,first.e.special,!first.e.reincarnateEligible);if(second){second.skill='backup';out.push(second)}}return out}
function addEnemy(boss=false){let a=empty();if(!a.length)return null;let p=randomItem(a),e={id:id++,type:boss?'boss':'enemy',r:p[0],c:p[1],hits:0,maxHits:boss?bmax():1,damage:boss?bdmg():edmg()};E.push(e);return e}
function renderIcons(){icons.innerHTML='';let all=[...sel,...classSel];if(!all.length){icons.innerHTML='<div class="empty-skills">尚未取得技能</div>';return}for(let sid of all){let s=skillById(sid),b=document.createElement('button');b.className='skill-icon'+(s&&s.kind==='class'?' class-skill':'');b.dataset.s=sid;b.innerHTML=s?'<span>'+s.icon+'</span><small class="gameLevelBadge">'+rank(s.id)+'</small>':'?';b.onclick=()=>s&&detail(s);icons.appendChild(b)}}
function render(){pieces.innerHTML='';let s=step();for(let e of E){let d=document.createElement('div');d.className='piece '+cls(e);d.dataset.id=e.id;d.style.transform='translate('+(e.c*s)+'px,'+(e.r*s)+'px)';d.innerHTML=inner(e);pieces.appendChild(d)}$('score').textContent=score;$('turn').textContent=turn;$('merges').textContent=merges;$('best').textContent=best;let p=$('profession');if(p)p.textContent=profession?PROFESSIONS[profession].icon+' '+PROFESSIONS[profession].name:'未選擇';renderIcons()}
function detail(s){let pr=RPGSave.progress(RPGSave.uses(s.id));panel.innerHTML='<div class="detail"><div class="big">'+s.icon+'</div><h2>'+s.name+'</h2><div class="detailLevel">'+pr.rank+' · 累積使用 '+pr.total+' 次'+(pr.rank==='MAX'?'':' · 本級進度 '+pr.current+'/'+pr.target)+'</div><p>'+s.desc+'</p><button class="close">關閉</button></div>';modal.classList.add('show');panel.querySelector('.close').onclick=()=>modal.classList.remove('show')}
function choiceHtml(s){return '<button class="choice" data-id="'+s.id+'"><span class="emoji">'+s.icon+'</span><strong>'+s.name+' <i class="choiceLevel">'+rank(s.id)+'</i></strong><span>'+s.desc+'</span></button>'}
function chooseGeneral(v){return new Promise(res=>{let p=S.filter(s=>!sel.includes(s.id)),o=[];while(p.length&&o.length<3)o.push(p.splice(Math.floor(Math.random()*p.length),1)[0]);if(!o.length){res();return}panel.innerHTML='<h2>NEW HERO '+v+'</h2><div class="lead">突破新的最高數字 · 選擇 1 個一般技能</div><div class="choices">'+o.map(choiceHtml).join('')+'</div>';modal.classList.add('show');panel.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{sel.push(b.dataset.id);modal.classList.remove('show');renderIcons();res()})})}
function chooseProfession(){return new Promise(res=>{panel.innerHTML='<h2>選擇特殊職業</h2><div class="lead">第一次合併 · 本局職業一旦選擇就固定</div><div class="choices">'+Object.values(PROFESSIONS).map(p=>'<button class="choice" data-id="'+p.id+'"><span class="emoji">'+p.icon+'</span><strong>'+p.name+'</strong><span>'+p.desc+'<br>進場：'+p.entry+'｜移動：'+p.move+'<br><small>職業基本能力不計技能等級</small></span></button>').join('')+'</div>';modal.classList.add('show');panel.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{profession=b.dataset.id;classChosen=true;nextSpecial=true;modal.classList.remove('show');render();res()})})}
function chooseClassSkill(){return new Promise(res=>{let p=currentClassPool().filter(s=>!classSel.includes(s.id)),o=[];while(p.length&&o.length<3)o.push(p.splice(Math.floor(Math.random()*p.length),1)[0]);if(!o.length){res();return}panel.innerHTML='<h2>BOSS REWARD</h2><div class="lead">'+PROFESSIONS[profession].icon+' '+PROFESSIONS[profession].name+' · 從尚未取得的職業／通用技能中三選一</div><div class="choices">'+o.map(choiceHtml).join('')+'</div>';modal.classList.add('show');panel.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{classSel.push(b.dataset.id);modal.classList.remove('show');renderIcons();maybeAwaken();res()})})}
function trig(sid,label){let s=skillById(sid);if(!s)return;useSkill(sid);let b=icons.querySelector('[data-s="'+sid+'"]');if(b)anim.play('pulse',{element:b});anim.play('skill-tag',{text:label||s.icon+' '+s.name+' '+rank(sid)});renderIcons()}function boardFx(icon){anim.play('board-wave');if(icon)anim.play('skill-tag',{text:icon})}
function deathFx(e){let d=document.createElement('div'),s=step();d.className='deathfx '+cls(e);d.style.transform='translate('+(e.c*s)+'px,'+(e.r*s)+'px)';d.innerHTML=inner(e);effects.appendChild(d);setTimeout(()=>d.remove(),DM)}function spawnFx(e,sid){let d=document.createElement('div'),s=step();d.className='spawnfx '+cls(e);d.style.transform='translate('+(e.c*s)+'px,'+(e.r*s)+'px)';d.innerHTML=inner(e);effects.appendChild(d);if(sid)trig(sid);setTimeout(()=>d.remove(),TIMING.SPAWN)}
function heal(e,n,ev,sid){if(!e||e.type!=='hero')return;let b=e.hits;e.hits=Math.max(0,(e.hits||0)-n);let h=b-e.hits;if(h)ev.push({t:'heal',e,n:h,s:sid})}function sdmg(){return 1}
function hitEnemy(e,n,ev,sid,icon='✨',source=null,arrow=false){if(!e||e.type==='hero'||rem(e)<=0)return;if(e.type==='boss'&&has('assault')){n++;useSkill('assault')}let d=Math.min(n,rem(e));e.hits+=d;ev.push({t:'damage',e,n:d,s:sid,icon,source,arrow})}
function punishTargets(h,a,level){if(level>=4)return livingEnemies().filter(e=>near8(h,e));if(level===3){let dr=Math.sign(a.r-h.r),dc=Math.sign(a.c-h.c);return livingEnemies().filter(e=>{let rr=e.r-h.r,cc=e.c-h.c;if(dr<0)return rr===-1&&Math.abs(cc)<=1;if(dr>0)return rr===1&&Math.abs(cc)<=1;if(dc<0)return cc===-1&&Math.abs(rr)<=1;return cc===1&&Math.abs(rr)<=1})}return rem(a)>0?[a]:[]}
function hitHero(h,n,a,ev){if(!h||rem(h)<=0||!a||rem(a)<=0)return;let d=n;if(h.guard){let owner=E.find(x=>x.id===h.guardBy&&x.type==='hero'&&x.special&&x.profession==='priest'&&rem(x)>0),savedBy=h.guardBy;let lvl=owner&&hasClass('priestPunish')?rankLevel('priestPunish'):0,keep=lvl>=2&&Math.random()<.20;h.guard=keep;h.guardBy=keep?savedBy:null;d=Math.max(0,n-1);ev.push({t:'buff',e:h,text:keep?'🛡️ -1 · 保留':'🛡️ -1'});if(owner&&lvl&&rem(a)>0){let targets=punishTargets(h,a,lvl),pd=sdmg();for(let e of targets)hitEnemy(e,pd,ev,'priestPunish','🔆',owner,true)}if(d<=0)return}d=Math.min(d,rem(h));h.hits+=d;if(d)ev.push({t:'damage',e:h,n:d,icon:'slash',enemyAttack:true})}
async function effectStage(ev){if(!ev.length)return;let ss=new Set;for(let x of ev){if(x.t!=='board'&&x.s)ss.add(x.s);if(x.t==='damage'){if(x.arrow&&x.source)anim.play('arrow',{source:x.source,target:x.e});else if(x.enemyAttack||x.icon==='slash')anim.play('slash',{target:x.e});else anim.play('burst',{target:x.e,icon:x.icon||'✨'});anim.play('damage',{target:x.e,value:x.n})}else if(x.t==='heal')anim.play('heal',{target:x.e,value:x.n});else if(x.t==='buff')anim.play('buff',{target:x.e,text:x.text});else if(x.t==='board')boardFx(x.icon)}for(let s of ss)trig(s);render();await wait(FX)}
function randomTargets(list,n){let p=list.slice(),out=[];while(p.length&&out.length<n)out.push(p.splice(Math.floor(Math.random()*p.length),1)[0]);return out}
function sweepTargets(hero,level){let es=livingEnemies().filter(e=>near8(hero,e));if(level>=4)return es;let dirs=[[-1,0],[1,0],[0,-1],[0,1]],valid=[];for(let[dr,dc]of dirs){let targets=es.filter(e=>dr?e.r-hero.r===dr&&Math.abs(e.c-hero.c)<=1:e.c-hero.c===dc&&Math.abs(e.r-hero.r)<=1);if(targets.length)valid.push(targets)}let chosen=randomTargets(valid,Math.min(level,valid.length)),seen=new Set,out=[];for(let group of chosen)for(let e of group)if(!seen.has(e.id)){seen.add(e.id);out.push(e)}return out}
function entryEvents(hero){let ev=[];if(!hero||!hero.special||rem(hero)<=0)return ev;let cast=()=>{let before=ev.length;if(hero.profession==='warrior'){let targets=hasClass('warSweep')?sweepTargets(hero,rankLevel('warSweep')):randomTargets(livingEnemies().filter(e=>near8(hero,e)),2),d=sdmg();for(let e of targets)hitEnemy(e,d,ev,'warriorEntry','⚔️',hero,false);if(hasClass('warSweep')&&ev.length>before)useSkill('warSweep')}else if(hero.profession==='priest'){let holy=hasClass('priestHolyHeal'),lvl=holy?rankLevel('priestHolyHeal'):0,hs=holy?livingHeroes():livingHeroes().filter(h=>near8(hero,h)),amount=holy?Math.min(lvl,3):1;for(let h of hs)heal(h,amount,ev,'priestEntry');if(holy&&lvl>=4){for(let h of hs){h.guard=true;h.guardBy=hero.id;ev.push({t:'buff',e:h,text:'🛡️ 守護'})}}if(holy&&ev.length>before)useSkill('priestHolyHeal')}};cast();if(hasClass('encore')){let before=ev.length;cast();if(ev.length>before)useSkill('encore')}return ev}
async function onSpecialEnter(hero){if(!hero||!hero.special)return;let ev=entryEvents(hero);if(ev.length)await settle(ev);if(hasClass('linkage')){let others=specialHeroes().filter(h=>h.id!==hero.id),did=false;for(let h of others){let lev=entryEvents(h);if(lev.length){did=true;await settle(lev)}}if(did)useSkill('linkage')}maybeAwaken()}
function dirVec(dir){return dir==='up'?[-1,0]:dir==='down'?[1,0]:dir==='left'?[0,-1]:[0,1]}function lineTargets(source,dir){let [dr,dc]=dirVec(dir),out=[];for(let k=1;k<N;k++){let r=source.r+dr*k,c=source.c+dc*k;if(r<0||r>=N||c<0||c>=N)break;let e=E.find(x=>x.type!=='hero'&&rem(x)>0&&x.r===r&&x.c===c);if(e)out.push(e)}return out}function farthestTargets(source,n,list=livingEnemies()){return list.slice().sort((a,b)=>{let da=Math.abs(a.r-source.r)+Math.abs(a.c-source.c),db=Math.abs(b.r-source.r)+Math.abs(b.c-source.c);return db-da||a.id-b.id}).slice(0,n)}
function warriorChargeEvents(moveMeta){let ev=[];for(let m of moveMeta){if(!m.blockedEnemy||!m.specialMoved||m.distance<1)continue;let h=E.find(x=>x.id===m.resultId),e=E.find(x=>x.id===m.blockedEnemy);if(!h||!e||!h.special||h.profession!=='warrior'||rem(h)<=0||rem(e)<=0)continue;hitEnemy(e,sdmg(),ev,'warriorCharge','⚔️',h,false);m.chargeHandled=true}return ev}
function moveClassEvents(moveMeta,dir){let ev=[];for(let m of moveMeta){let h=E.find(x=>x.id===m.resultId);if(!h||!h.special||rem(h)<=0||!m.specialMoved)continue;if(h.profession==='warrior'){if(m.blockedEnemy&&!m.chargeHandled&&m.distance>=1){let e=E.find(x=>x.id===m.blockedEnemy);if(e)hitEnemy(e,sdmg(),ev,'warriorCharge','⚔️',h,false)}if(hasClass('warImpact')&&m.distance>=2){let es=livingEnemies().filter(e=>near8(h,e)),count=rankLevel('warImpact');for(let e of randomTargets(es,count))hitEnemy(e,sdmg(),ev,'warImpact','💢',h,false)}}else if(h.profession==='ranger'&&m.distance>0){let fireFarshot=sid=>{let far;if(hasClass('rangerSnipe')){let lvl=rankLevel('rangerSnipe');far=lvl>=4?randomTargets(livingEnemies(),3):farthestTargets(h,lvl+1,livingEnemies().filter(e=>!near8(h,e)));if(far.length)useSkill('rangerSnipe')}else far=farthestTargets(h,1,livingEnemies().filter(e=>!near8(h,e)));if(far.length){let d=sdmg();for(let e of far)hitEnemy(e,d,ev,sid,'🏹',h,true)}};fireFarshot('rangerFarshot');if(hasClass('rangerQuickShot')){let lvl=rankLevel('rangerQuickShot'),eligible=lvl>=4?m.distance>=1:m.distance>=2;if(eligible){let shots=Math.min(lvl,3);for(let i=0;i<shots;i++)fireFarshot('rangerQuickShot')}}let reverse=dir==='up'?'down':dir==='down'?'up':dir==='left'?'right':'left',es=lineTargets(h,reverse);if(es.length){let d=sdmg();hitEnemy(es[0],d,ev,'rangerBackshot','🏹',h,true)}}else if(h.profession==='priest'){for(let ally of livingHeroes().filter(x=>Math.abs(x.r-h.r)<=1&&Math.abs(x.c-h.c)<=1)){ally.guard=true;ally.guardBy=h.id;ev.push({t:'buff',e:ally,text:'🛡️ -1'})}}}return ev}
function smashTargets(h,level){let es=livingEnemies();if(level>=4)return es;let out=es.filter(e=>{let dr=e.r-h.r,dc=e.c-h.c;if(level===1)return Math.abs(dr)+Math.abs(dc)===1;if(dr===0||dc===0)return true;return level>=3&&Math.abs(dr)===1&&Math.abs(dc)===1});return out}
function mergeClassEvents(mergeMeta){let ev=[];for(let m of mergeMeta){let h=E.find(x=>x.id===m.resultId);if(m.ascended)useSkill('ascend');if(!h||!h.special||rem(h)<=0||!m.specialParticipant)continue;if(h.profession==='warrior'&&hasClass('warSmash')){let d=sdmg();for(let e of smashTargets(h,rankLevel('warSmash')))hitEnemy(e,d,ev,'warSmash','🔨',h,false)}else if(h.profession==='ranger'&&hasClass('rangerRain')){let lvl=rankLevel('rangerRain'),eligible=livingEnemies().filter(e=>!near8(h,e)),targets=lvl>=4?livingEnemies():randomTargets(eligible,lvl+1),d=sdmg();for(let e of targets)hitEnemy(e,d,ev,'rangerRain','🌧️',h,true)}}return ev}
function deathTriggerEvents(wave){let ev=[];for(let e of wave){if(e.type==='hero'){if(has('deathBlast')){let es=livingEnemies().filter(x=>Math.abs(x.r-e.r)<=1&&Math.abs(x.c-e.c)<=1);if(es.length)hitEnemy(randomItem(es),sdmg(),ev,'deathBlast','💣')}if(has('legacy')){legacy=true;ev.push({t:'board',icon:'👻 遺志已準備'})}}}return ev}
function tryResurrect(hero){if(!hero||hero.type!=='hero'||hero.revived||!hasClass('priestRevive'))return null;let priest=specialHeroes().find(p=>p.profession==='priest'&&near8(p,hero));if(!priest)return null;let hp=Math.min(rankLevel('priestRevive'),3,max(hero));hero.hits=max(hero)-hp;hero.revived=true;return{t:'heal',e:hero,n:hp,s:'priestRevive'}}
function reviveEnemyConversions(wave){if(!hasClass('priestRevive')||rankLevel('priestRevive')<4)return[];let priests=specialHeroes().filter(p=>p.profession==='priest'),out=[];for(let e of wave){if(e.type==='hero'||!priests.some(p=>near8(p,e)))continue;if(E.some(x=>x.type==='hero'&&x.r===e.r&&x.c===e.c&&rem(x)>0))continue;out.push({r:e.r,c:e.c})}return out}
async function processDeathWave(){let candidates=E.filter(e=>rem(e)<=0&&!e.resolvedDeath),rev=[];for(let e of candidates){if(e.type==='hero'){let r=tryResurrect(e);if(r)rev.push(r)}}if(rev.length)await effectStage(rev);let wave=E.filter(e=>rem(e)<=0&&!e.resolvedDeath);if(!wave.length)return false;let conversions=reviveEnemyConversions(wave);for(let e of wave){e.resolvedDeath=true;deathFx(e)}await wait(DM);let bossKills=0;for(let e of wave){if(e.type==='hero'){heroesLost++;deathCount++;if(e.special&&hasClass('reincarnate')&&e.reincarnateEligible){e.reincarnateEligible=false;reincarnateQueue++;useSkill('reincarnate')}if(has('blood')&&deathCount>=3&&!bloodReady)bloodReady=true;let riskOn=has('risk'),loss=Math.min(score,hv(e)*(riskOn?2:1));if(riskOn&&loss>0)useSkill('risk');score-=loss;deathPenalty+=loss}else{enemyDefeated++;if(e.type==='boss'){let gain=100;score+=gain;bossScore+=gain;bd++;bl++;bactive=false;next=turn+BI;bossKills++}else{let riskOn=has('risk'),gain=riskOn?40:20;if(riskOn)useSkill('risk');score+=gain;enemyScore+=gain}}}E=E.filter(e=>!e.resolvedDeath);for(let c of conversions){if(at(c.r,c.c))continue;let h={id:id++,type:'hero',tier:16,r:c.r,c:c.c,hits:13,special:false,profession:null,revived:false,guard:false,guardBy:null,reincarnateEligible:false};E.push(h);render();spawnFx(h,'priestRevive')}render();let ev=deathTriggerEvents(wave);if(ev.length)await effectStage(ev);for(let i=0;i<bossKills;i++)if(profession)await chooseClassSkill();maybeAwaken();return true}
async function settle(ev){if(ev.length)await effectStage(ev);for(let g=0;g<16;g++){if(!await processDeathWave())break}}
function rec(e,fr,fc,tr,tc){return{id:e.id,fr,fc,tr,tc,cl:cls(e),html:inner(e)}}
async function animateMoves(ms){if(!ms.length)return;let s=step();for(let m of ms){let b=pieces.querySelector('[data-id="'+m.id+'"]');if(b)b.classList.add('hideForMove');let g=document.createElement('div');g.className='moveghost '+m.cl;g.innerHTML=m.html;g.style.transform='translate('+(m.fc*s)+'px,'+(m.fr*s)+'px)';effects.appendChild(g);m.el=g}requestAnimationFrame(()=>requestAnimationFrame(()=>ms.forEach(m=>m.el.style.transform='translate('+(m.tc*s)+'px,'+(m.tr*s)+'px)')));await wait(MM);ms.forEach(m=>m.el.remove())}
function plan(dir){let L=JSON.parse(JSON.stringify(E)),before=JSON.stringify(L.map(x=>[x.id,x.r,x.c,x.tier,x.special])),hs=L.filter(x=>x.type==='hero'&&rem(x)>0),[dr,dc]=dirVec(dir);hs.sort((a,b)=>dir==='left'?a.c-b.c:dir==='right'?b.c-a.c:dir==='up'?a.r-b.r:b.r-a.r);let merged=new Set,mids=[],ms=[],contacts=[],moveMeta=[],mergeMeta=[];for(let h of hs){if(!L.some(x=>x.id===h.id))continue;let sr=h.r,sc=h.c,origSpecial=!!h.special,origProf=h.profession;while(1){let nr=h.r+dr,nc=h.c+dc;if(nr<0||nr>=N||nc<0||nc>=N)break;let o=L.find(x=>x.id!==h.id&&x.r===nr&&x.c===nc);if(!o){h.r=nr;h.c=nc;continue}if(o.type==='hero'&&o.tier===h.tier&&!merged.has(o.id)){let nt=o.tier*2,bothSpecial=!!o.special&&origSpecial,ascended=bothSpecial&&hasClass('ascend');if(ascended)nt=o.tier*4;let r=Math.min(nt,rem(o)+rem(h));ms.push(rec(h,sr,sc,o.r,o.c));o.tier=nt;o.hits=Math.max(0,nt-r);o.special=!!o.special||origSpecial;o.profession=o.special?(o.profession||origProf||profession):null;o.reincarnateEligible=!!(o.reincarnateEligible||h.reincarnateEligible);L=L.filter(x=>x.id!==h.id);merged.add(o.id);mids.push(o.id);let dist=Math.abs(o.r-sr)+Math.abs(o.c-sc);moveMeta.push({resultId:o.id,specialMoved:origSpecial,distance:dist,blockedEnemy:null});mergeMeta.push({resultId:o.id,specialParticipant:!!o.special,ascended});break}if(o.type!=='hero'){let dist=Math.abs(h.r-sr)+Math.abs(h.c-sc);contacts.push({h:h.id,e:o.id,moved:dist>0});moveMeta.push({resultId:h.id,specialMoved:origSpecial,distance:dist,blockedEnemy:o.id});break}break}if(L.some(x=>x.id===h.id)&&(sr!==h.r||sc!==h.c)){ms.push(rec(h,sr,sc,h.r,h.c));if(!moveMeta.some(x=>x.resultId===h.id))moveMeta.push({resultId:h.id,specialMoved:origSpecial,distance:Math.abs(h.r-sr)+Math.abs(h.c-sc),blockedEnemy:null})}}return{changed:contacts.length||before!==JSON.stringify(L.map(x=>[x.id,x.r,x.c,x.tier,x.special])),L,ms,mids,contacts,moveMeta,mergeMeta}}
function canMove(){return['left','right','up','down'].some(d=>plan(d).changed)}
async function mergeFx(ids){if(!ids.length)return;for(let mid of ids){let h=E.find(x=>x.id===mid);if(h){let d=document.createElement('div'),s=step();d.className='mergefx';d.style.transform='translate('+(h.c*s)+'px,'+(h.r*s)+'px)';d.innerHTML=inner(h);effects.appendChild(d);setTimeout(()=>d.remove(),GM)}}await wait(GM)}
function mergeEvents(ids,moved){let ev=[],records=[];for(let mid of ids){let h=E.find(x=>x.id===mid);if(!h)continue;merges++;let v=hv(h);score+=v;mergeScore+=v;if(has('resonance')&&merges%5===0){let d=sdmg();for(let e of livingEnemies())hitEnemy(e,d,ev,'resonance','💥')}if(has('precision')&&merges%15===0){let es=livingEnemies().sort(()=>Math.random()-.5).slice(0,3);for(let e of es)hitEnemy(e,1,ev,'precision','📐')}if(legacy){let es=livingEnemies();if(es.length)hitEnemy(randomItem(es),sdmg(),ev,'legacy','👻');legacy=false}if(v>best){best=v;RPGSave.recordBestHero(v);records.push(v)}}if(has('overload')&&ids.length>=2){let d=sdmg();for(let e of livingEnemies())hitEnemy(e,d,ev,'overload','🔥')}if(has('wind')&&moved>=4){let es=livingEnemies();if(es.length)hitEnemy(randomItem(es),sdmg(),ev,'wind','🌪️')}return{ev,records}}
function enemyPlan(){let ms=[],att=[];for(let e of livingEnemies()){let a=livingHeroes().find(h=>Math.abs(h.r-e.r)+Math.abs(h.c-e.c)===1);if(a){att.push({e:e.id,h:a.id});continue}let hs=livingHeroes();if(!hs.length)break;hs.sort((a,b)=>(Math.abs(a.r-e.r)+Math.abs(a.c-e.c))-(Math.abs(b.r-e.r)+Math.abs(b.c-e.c)));let h=hs[0],opts=[[Math.sign(h.r-e.r),0],[0,Math.sign(h.c-e.c)]],sr=e.r,sc=e.c;for(let[rr,cc]of opts){let nr=e.r+rr,nc=e.c+cc;if((rr||cc)&&nr>=0&&nr<N&&nc>=0&&nc<N&&!at(nr,nc,e.id)){e.r=nr;e.c=nc;ms.push(rec(e,sr,sc,nr,nc));break}}}return{ms,att}}
async function enemyPhase(){let p=enemyPlan();if(p.ms.length){render();await animateMoves(p.ms);render()}let ev=[];for(let a of p.att){let h=E.find(x=>x.id===a.h),e=E.find(x=>x.id===a.e);if(h&&e&&rem(h)>0&&rem(e)>0)hitHero(h,e.damage,e,ev)}await settle(ev)}
async function postTurn(){let hs=addHero();for(let h of hs){render();spawnFx(h.e,h.skill);await wait(TIMING.SPAWN);if(h.e.special)await onSpecialEnter(h.e)}if(turn%2===0){if(skipEnemy){skipEnemy=false;trig('swift','👟 疾行')}else{let e=addEnemy();if(e){render();spawnFx(e);await wait(TIMING.SPAWN)}}}if(turn>=next&&!bactive){let b=addEnemy(true);if(b){bactive=true;render();spawnFx(b);await wait(TIMING.SPAWN);let be=[];if(has('firstStrike'))hitEnemy(b,2,be,'firstStrike','⚡');await settle(be)}}}
async function move(d){if(ended||busy||modal.classList.contains('show'))return;let p=plan(d);if(!p.changed){check();render();return}busy=true;moves++;score++;moveScore++;if(has('swift')&&moves%5===0)skipEnemy=true;if(has('luck')&&moves%10===0)luckReady=true;await animateMoves(p.ms);E=p.L;render();await mergeFx(p.mids);let chargeEv=warriorChargeEvents(p.moveMeta);if(chargeEv.length)await settle(chargeEv);let ev=[];for(let c of p.contacts){let h=E.find(x=>x.id===c.h),e=E.find(x=>x.id===c.e);if(h&&e&&rem(e)>0)hitHero(h,e.damage,e,ev)}ev.push(...moveClassEvents(p.moveMeta,d));let mr=mergeEvents(p.mids,p.ms.length);ev.push(...mr.ev,...mergeClassEvents(p.mergeMeta));await settle(ev);if(p.mids.length&&!classChosen)await chooseProfession();for(let v of mr.records)await chooseGeneral(v);noMerge=p.mids.length?0:noMerge+1;if(has('momentum')&&noMerge>=3){let me=[];for(let h of livingHeroes())heal(h,1,me,'momentum');noMerge=0;await settle(me)}maybeAwaken();if(!livingHeroes().length){check();busy=false;return}turn++;render();await enemyPhase();if(!livingHeroes().length){check();busy=false;return}await postTurn();render();check();busy=false}
function check(){if(!livingHeroes().length)return end('隊伍全滅');if(!canMove())return end('無法移動')}
function end(t){if(ended)return;ended=true;RPGSave.recordRun({score,moves,merges,enemyDefeated,bossKills:bd,heroesLost,bestHero:best});let all=[...sel,...classSel],skillHtml=all.length?all.map(sid=>{let s=skillById(sid);return '<div class="resultSkill" title="'+s.desc+'"><b>'+s.icon+'</b><span>'+s.name+' '+rank(s.id)+'</span></div>'}).join(''):'<div class="noSkill">本局尚未取得技能</div>';let classInfo=profession?'<div class="skillCard"><h3>特殊職業</h3><div class="classSummary">'+PROFESSIONS[profession].icon+' '+PROFESSIONS[profession].name+(awakened?' · 👑 已覺醒':'')+'</div></div>':'';let skills=classInfo+'<div class="skillCard"><h3>本局取得技能</h3><div class="resultSkills">'+skillHtml+'</div></div>';panel.innerHTML=renderRunHistory({title:t,score,scoreRows:[{label:'移動得分',value:'+'+moveScore,className:'plus'},{label:'合併／突破得分',value:'+'+mergeScore,className:'plus'},{label:'擊殺暗影刺客',value:'+'+enemyScore,className:'plus'},{label:'擊敗 Boss',value:'+'+bossScore,className:'plus'},{label:'英雄死亡',value:'−'+deathPenalty,className:'minus'}],historyRows:[{label:'特殊職業',value:profession?PROFESSIONS[profession].name:'未選擇'},{label:'存活回合',value:turn},{label:'移動次數',value:moves},{label:'合併次數',value:merges},{label:'擊殺敵人',value:enemyDefeated},{label:'其中 Boss',value:bd},{label:'英雄死亡',value:heroesLost},{label:'最高英雄數字',value:best}],skillsHtml:skills,backHtml:'<a href="./">回到主選單</a>'});modal.classList.add('show');$('again').onclick=reset}
function reset(){E=[];turn=0;merges=0;id=1;ended=false;busy=false;score=0;moves=0;best=1;bl=1;bd=0;next=20;bactive=false,spawn=0,noMerge=0,legacy=false,sel=[],classSel=[],profession=null,classChosen=false,nextSpecial=false,awakened=false,reincarnateQueue=0,claimedScoreMilestone=0,specialMilestoneQueue=0,moveScore=0,mergeScore=0,enemyScore=0,bossScore=0,deathPenalty=0,heroesLost=0,enemyDefeated=0,deathCount=0,bloodReady=false,skipEnemy=false,luckReady=false;effects.innerHTML='';modal.classList.remove('show');makeHero(2,false);makeHero(2,false);makeHero(2,false);render()}
bindDirectionalInput({board,onMove:move,threshold:25,keyMap:{ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}});window.addEventListener('resize',render);$('restart').onclick=reset;reset();
window.__V2_TEST__={hv,max,rem,plan,mergeEvents,deathTriggerEvents,getSkills:()=>S.slice(),getProfessions:()=>PROFESSIONS,getClassSkills:()=>({CLASS_SKILLS,COMMON_SKILLS}),entryEvents,moveClassEvents,mergeClassEvents,rankLevel,sweepTargets,smashTargets,punishTargets};
})();