(function(){'use strict';
const bootError=document.getElementById('bootError');
function fail(msg){if(bootError){bootError.style.display='block';bootError.textContent='v0.6 模組載入失敗：'+msg}console.error(msg)}
fetch('game.js?v=20260915c').then(r=>{if(!r.ok)throw new Error('game.js '+r.status);return r.text()}).then(src=>{
const patches=[
["hv=e=>(e.tier||2)/2,max=e=>e.type==='hero'?e.tier:e.maxHits,rem=e=>Math.max(0,max(e)-(e.hits||0))","hv=e=>(e.tier||2)/2,heroMax=tier=>1+Math.log2(Math.max(2,tier||2)),enemyMax=()=>Math.ceil((bd+1)/2),max=e=>e.type==='hero'?heroMax(e.tier):e.maxHits,rem=e=>Math.max(0,max(e)-(e.hits||0))"],
["healthBar(rem(e),e.tier,'hero')","healthBar(rem(e),max(e),'hero')"],
["return '<div class=\"icon\">🥷</div><div class=\"name\">暗影刺客</div><div class=\"unitMeta\">ATK '+e.damage+'</div>'","return '<div class=\"icon\">🥷</div><div class=\"name\">暗影刺客</div>'+(e.maxHits>1?healthBar(rem(e),e.maxHits,'enemy','ATK '+e.damage):'<div class=\"unitMeta\">ATK '+e.damage+'</div>')"],
["maxHits:boss?bmax():1,damage:boss?bdmg():edmg()","maxHits:boss?bmax():enemyMax(),damage:boss?bdmg():edmg()"],
["let r=Math.min(nt,rem(o)+rem(h));ms.push(rec(h,sr,sc,o.r,o.c));o.tier=nt;o.hits=Math.max(0,nt-r);","let r=Math.min(heroMax(nt),rem(o)+rem(h));ms.push(rec(h,sr,sc,o.r,o.c));o.tier=nt;o.hits=Math.max(0,heroMax(nt)-r);"],
["tier:16,r:c.r,c:c.c,hits:13,special:false","tier:16,r:c.r,c:c.c,hits:2,special:false"],
["};fireFarshot('rangerFarshot');if(hasClass('rangerQuickShot'))","};if(Math.random()<.50)fireFarshot('rangerFarshot');if(hasClass('rangerQuickShot'))"],
["window.__V2_TEST__={hv,max,rem,plan","window.__V2_TEST__={hv,heroMax,enemyMax,max,rem,plan"]
];
for(const [from,to] of patches){if(!src.includes(from))throw new Error('找不到預期的 v0.6 程式片段');src=src.replace(from,to)}
function replaceBlock(start,end,replacement){let a=src.indexOf(start);if(a<0)throw new Error('找不到 '+start);let b=src.indexOf(end,a);if(b<0)throw new Error('找不到 '+end);src=src.slice(0,a)+replacement+'\n'+src.slice(b)}
// v0.6 profession selector: tabs + horizontal swipe + full base-skill descriptions.
replaceBlock('function chooseProfession(){','function chooseClassSkill(){',`function chooseProfession(){return new Promise(res=>{let ps=Object.values(PROFESSIONS),idx=0;let detail=p=>p.id==='warrior'?[['⚔️ 迎戰','特殊戰士接觸敵人時，對接觸的敵人造成 1 點傷害。'],['突進','特殊戰士實際移動後接觸敵人時發動近戰攻擊。']]:p.id==='ranger'?[['🏹 遠射','遊俠實際移動後，有 50% 機率對周圍 8 格以外最遠的敵人造成 1 點傷害。'],['↩️ 回身射擊','遊俠移動後，向本次移動的反方向射擊；該方向有敵人時攻擊第一個敵人。']]:[['✨ 治癒波','特殊祭司進場時，治療周圍 8 格內的我方單位 1 HP。'],['🛡️ 守護','祭司實際移動後，自己與周圍 8 格內友方獲得守護；下一次受到傷害時傷害 -1，之後消耗。']];let draw=()=>{let p=ps[idx],skills=detail(p);panel.innerHTML='<h2>選擇特殊職業</h2><div class="lead">第一次合併 · 本局職業一旦選擇就固定</div><div class="professionTabs">'+ps.map((x,i)=>'<button class="professionTab '+(i===idx?'active':'')+'" data-i="'+i+'">'+x.icon+' '+x.name+'</button>').join('')+'</div><div class="professionSwipe"><div class="professionHero"><span>'+p.icon+'</span><div><h3>'+p.name+'</h3><p>'+p.desc+'</p></div></div><div class="professionBasics">'+skills.map(s=>'<div class="professionBasic"><b>'+s[0]+'</b><p>'+s[1]+'</p></div>').join('')+'</div><div class="professionFixed">職業基礎技能為固定能力，不計技能熟練度／等級。</div><button class="professionSelect" data-id="'+p.id+'">選擇 '+p.icon+' '+p.name+'</button><div class="professionSwipeHint">左右滑動切換職業</div></div>';panel.querySelectorAll('.professionTab').forEach(b=>b.onclick=()=>{idx=Number(b.dataset.i);draw()});panel.querySelector('.professionSelect').onclick=b=>{profession=b.currentTarget.dataset.id;classChosen=true;nextSpecial=true;modal.classList.remove('show');render();res()};let area=panel.querySelector('.professionSwipe'),sx=0,sy=0;area.addEventListener('touchstart',e=>{let t=e.changedTouches[0];sx=t.clientX;sy=t.clientY},{passive:true});area.addEventListener('touchend',e=>{let t=e.changedTouches[0],dx=t.clientX-sx,dy=t.clientY-sy;if(Math.abs(dx)>=50&&Math.abs(dx)>Math.abs(dy)*1.2){let ni=idx+(dx<0?1:-1);if(ni>=0&&ni<ps.length){idx=ni;draw()}}},{passive:true})};modal.classList.add('show');draw()})}`);
// Game-over mobility ignores pure collision: a direction is legal only when a hero actually moves or merges.
replaceBlock('function canMove(){','async function mergeFx',`function canMove(){return['left','right','up','down'].some(d=>{let p=plan(d);return p.ms.length>0||p.mids.length>0})}`);
// Revived special heroes re-enter immediately. Their entry/encore/linkage chain resolves inside the current phase.
replaceBlock('async function processDeathWave(){','async function settle(ev)',`async function processDeathWave(){let candidates=E.filter(e=>rem(e)<=0&&!e.resolvedDeath),rev=[],revived=[];for(let e of candidates){if(e.type==='hero'){let r=tryResurrect(e);if(r){rev.push(r);revived.push(e)}}}if(rev.length)await effectStage(rev);for(let h of revived)if(h.special&&rem(h)>0)await onSpecialEnter(h);let wave=E.filter(e=>rem(e)<=0&&!e.resolvedDeath);if(!wave.length)return false;let conversions=reviveEnemyConversions(wave);for(let e of wave){e.resolvedDeath=true;deathFx(e)}await wait(DM);let bossKills=0;for(let e of wave){if(e.type==='hero'){heroesLost++;deathCount++;if(e.special&&hasClass('reincarnate')&&e.reincarnateEligible){e.reincarnateEligible=false;reincarnateQueue++;useSkill('reincarnate')}if(has('blood')&&deathCount>=3&&!bloodReady)bloodReady=true;let riskOn=has('risk'),loss=Math.min(score,hv(e)*(riskOn?2:1));if(riskOn&&loss>0)useSkill('risk');score-=loss;deathPenalty+=loss}else{enemyDefeated++;if(e.type==='boss'){let gain=100;score+=gain;bossScore+=gain;bd++;bl++;bactive=false;next=turn+BI;bossKills++}else{let riskOn=has('risk'),gain=riskOn?40:20;if(riskOn)useSkill('risk');score+=gain;enemyScore+=gain}}}E=E.filter(e=>!e.resolvedDeath);for(let c of conversions){if(at(c.r,c.c))continue;let h={id:id++,type:'hero',tier:16,r:c.r,c:c.c,hits:2,special:false,profession:null,revived:false,guard:false,guardBy:null,reincarnateEligible:false};E.push(h);render();spawnFx(h,'priestRevive');await wait(TIMING.SPAWN)}render();let ev=deathTriggerEvents(wave);if(ev.length)await effectStage(ev);for(let i=0;i<bossKills;i++)if(profession)await chooseClassSkill();maybeAwaken();return true}`);
// A phase-start spawn is allowed to act in that same phase. Mid-phase summons are not added to the current queue.
replaceBlock('function enemyPlan(){','async function move(d)',`async function enemyAct(e){if(!e||rem(e)<=0)return;let hs=livingHeroes();if(!hs.length)return;let adjacent=hs.filter(h=>Math.abs(h.r-e.r)+Math.abs(h.c-e.c)===1).sort((a,b)=>a.id-b.id);if(!adjacent.length){hs=hs.slice().sort((a,b)=>(Math.abs(a.r-e.r)+Math.abs(a.c-e.c))-(Math.abs(b.r-e.r)+Math.abs(b.c-e.c))||a.id-b.id);let h=hs[0],opts=[[Math.sign(h.r-e.r),0],[0,Math.sign(h.c-e.c)]],sr=e.r,sc=e.c;for(let[rr,cc]of opts){let nr=e.r+rr,nc=e.c+cc;if((rr||cc)&&nr>=0&&nr<N&&nc>=0&&nc<N&&!at(nr,nc,e.id)){let m=rec(e,sr,sc,nr,nc);e.r=nr;e.c=nc;render();await animateMoves([m]);render();break}}adjacent=livingHeroes().filter(h=>Math.abs(h.r-e.r)+Math.abs(h.c-e.c)===1).sort((a,b)=>a.id-b.id)}if(adjacent.length&&rem(e)>0){let ev=[];hitHero(adjacent[0],e.damage,e,ev);await settle(ev)}}
async function spawnEnemyPhase(){if(turn%2===0){if(skipEnemy){skipEnemy=false;trig('swift','👟 疾行')}else{let e=addEnemy();if(e){render();spawnFx(e);await wait(TIMING.SPAWN)}}}if(turn>=next&&!bactive){let b=addEnemy(true);if(b){bactive=true;render();spawnFx(b);await wait(TIMING.SPAWN);let be=[];if(has('firstStrike'))hitEnemy(b,2,be,'firstStrike','⚡');await settle(be)}}}
async function enemyPhase(){await spawnEnemyPhase();let normals=livingEnemies().filter(e=>e.type==='enemy').sort((a,b)=>a.id-b.id).map(e=>e.id);let bosses=livingEnemies().filter(e=>e.type==='boss').sort((a,b)=>a.id-b.id).map(e=>e.id);for(let eid of normals){let e=E.find(x=>x.id===eid);if(e&&rem(e)>0)await enemyAct(e);if(!livingHeroes().length)return}for(let eid of bosses){let e=E.find(x=>x.id===eid);if(e&&rem(e)>0)await enemyAct(e);if(!livingHeroes().length)return}}
async function playerPhaseStart(){let hs=addHero();for(let h of hs){render();spawnFx(h.e,h.skill);await wait(TIMING.SPAWN);if(h.e.special)await onSpecialEnter(h.e)}render();check()}`);
// Player action: collision is self-inflicted 1 damage, but Guard still blocks it and Punish reflects it.
replaceBlock('async function move(d){','function check(){',`async function move(d){if(ended||busy||modal.classList.contains('show'))return;let p=plan(d);if(!(p.ms.length||p.mids.length)){check();render();return}busy=true;moves++;score++;moveScore++;if(has('swift')&&moves%5===0)skipEnemy=true;if(has('luck')&&moves%10===0)luckReady=true;await animateMoves(p.ms);E=p.L;render();await mergeFx(p.mids);let chargeEv=warriorChargeEvents(p.moveMeta);if(chargeEv.length)await settle(chargeEv);for(let c of p.contacts){let h=E.find(x=>x.id===c.h),e=E.find(x=>x.id===c.e);if(h&&e&&rem(h)>0&&rem(e)>0){let cev=[];hitHero(h,1,e,cev);await settle(cev)}}let moveEv=moveClassEvents(p.moveMeta,d);if(moveEv.length)await settle(moveEv);let mr=mergeEvents(p.mids,p.ms.length);if(mr.ev.length)await settle(mr.ev);let mergeEv=mergeClassEvents(p.mergeMeta);if(mergeEv.length)await settle(mergeEv);if(p.mids.length&&!classChosen)await chooseProfession();for(let v of mr.records)await chooseGeneral(v);noMerge=p.mids.length?0:noMerge+1;if(has('momentum')&&noMerge>=3){let me=[];for(let h of livingHeroes())heal(h,1,me,'momentum');noMerge=0;await settle(me)}maybeAwaken();if(!livingHeroes().length){check();busy=false;return}await enemyPhase();if(!livingHeroes().length){check();busy=false;return}turn++;await playerPhaseStart();render();busy=false}`);
// Initial board is Player Phase 0 setup; later Player phases begin with spawn -> entry resolution -> mobility check.
replaceBlock('function reset(){','bindDirectionalInput(',`function reset(){E=[];turn=0;merges=0;id=1;ended=false;busy=false;score=0;moves=0;best=1;bl=1;bd=0;next=20;bactive=false,spawn=0,noMerge=0,legacy=false,sel=[],classSel=[],profession=null,classChosen=false,nextSpecial=false,awakened=false,reincarnateQueue=0,claimedScoreMilestone=0,specialMilestoneQueue=0,moveScore=0,mergeScore=0,enemyScore=0,bossScore=0,deathPenalty=0,heroesLost=0,enemyDefeated=0,deathCount=0,bloodReady=false,skipEnemy=false,luckReady=false;effects.innerHTML='';modal.classList.remove('show');makeHero(2,false);makeHero(2,false);makeHero(2,false);render();check()}`);
(0,eval)(src+'\n//# sourceURL=rpg-v2-v0-6/game-v06-runtime.js');
}).catch(e=>fail(e.message));
})();