(function(){'use strict';
const bootError=document.getElementById('bootError');
function fail(msg){if(bootError){bootError.style.display='block';bootError.textContent='v0.6 模組載入失敗：'+msg}console.error(msg)}
fetch('game.js?v=20260915c').then(r=>{if(!r.ok)throw new Error('game.js '+r.status);return r.text()}).then(src=>{
const patches=[
["hv=e=>(e.tier||2)/2,max=e=>e.type==='hero'?e.tier:e.maxHits,rem=e=>Math.max(0,max(e)-(e.hits||0))","hv=e=>(e.tier||2)/2,heroMax=tier=>1+Math.log2(Math.max(2,tier||2)),enemyMax=()=>Math.ceil((bd+1)/2),max=e=>e.type==='hero'?heroMax(e.tier):e.maxHits,rem=e=>Math.max(0,max(e)-(e.hits||0))"],
["healthBar(rem(e),e.tier,'hero')","healthBar(rem(e),max(e),'hero')"],
["return '<div class=\"icon\">🥷</div><div class=\"name\">暗影刺客</div><div class=\"unitMeta\">ATK '+e.damage+'</div>'","return '<div class=\"icon\">🥷</div><div class=\"name\">暗影刺客</div>'+(e.maxHits>1?healthBar(rem(e),e.maxHits,'enemy','ATK '+e.damage):'<div class=\"unitMeta\">ATK '+e.damage+'</div>')"],
["maxHits:boss?bmax():1,damage:boss?bdmg():edmg()","maxHits:boss?bmax():enemyMax(),damage:boss?bdmg():edmg()"],
["let r=Math.min(nt,rem(o)+rem(h));ms.push(rec(h,sr,sc,o.r,o.c));o.tier=nt;o.hits=Math.max(0,nt-r);","let r=Math.min(heroMax(nt),rem(o)+rem(h));ms.push(rec(h,sr,sc,o.r,o.c));o.tier=nt;o.hits=Math.max(0,heroMax(nt)-r);"],
["tier:16,r:c.r,c:c.c,hits:13,special:false","tier:16,r:c.r,c:c.c,hits:2,special:false"],
["};fireFarshot('rangerFarshot');if(hasClass('rangerQuickShot'))","};if(Math.random()<.50)fireFarshot('rangerFarshot');if(hasClass('rangerQuickShot'))"],
["window.__V2_TEST__={hv,max,rem,plan","window.__V2_TEST__={hv,heroMax,enemyMax,max,rem,plan"]
];
for(const [from,to] of patches){if(!src.includes(from))throw new Error('找不到預期的 v0.6 程式片段');src=src.replace(from,to)}
function replaceBlock(start,end,replacement){let a=src.indexOf(start);if(a<0)throw new Error('找不到 '+start);let b=src.indexOf(end,a);if(b<0)throw new Error('找不到 '+end);src=src.slice(0,a)+replacement+'\n'+src.slice(b)}
// General-skill mastery descriptions.
const desc={swift:'LV1/LV2/LV3 每 5/4/3 次有效移動，下一個 Enemy Phase 不生成普通敵人；MAX 每 3 次觸發，且該 Enemy Phase 所有普通敵人跳過行動，Boss 不受影響。',wind:'一次滑動實際移動英雄達門檻時：LV1 移動≥4 攻擊隨機 1 名；LV2 移動≥4 攻擊 2 名；LV3 移動≥3 攻擊 2 名；MAX 移動≥3 攻擊全場敵人，各 1 傷害。',momentum:'連續 3 回合沒有合併：LV1/LV2/LV3 全體友方恢復 1/2/3 HP；MAX 恢復 3 HP 並讓全體友方獲得守護。',resonance:'每 5 次合併：LV1/LV2/LV3 隨機 3/4/5 名不同敵人各受 1 傷害；MAX 全場所有敵人各受 1 傷害。',overload:'同一次滑動至少 2 次合併：LV1/LV2/LV3 全場敵人受 1/2/3 傷害；MAX 傷害等於本次合併次數，並讓全體友方獲得守護。',luck:'每 10 次有效移動，下一個普通英雄生成時提升一階的機率為 LV1 25%、LV2 50%、LV3 75%、MAX 100%。',deathBlast:'我方單位確實死亡時，對死亡位置周圍 8 格：LV1/LV2/LV3 隨機 1/2/3 名不同敵人各造成 1 傷害；MAX 攻擊範圍內全部敵人。復甦成功不觸發。',legacy:'我方單位確實死亡後，下一次合併：LV1/LV2/LV3 隨機攻擊 1/2/3 名不同敵人各 1 傷害；MAX 全場敵人各受 1 傷害。不累積多次 Ready。',blood:'每 3 名我方單位確實死亡，下一個生成英雄：LV1/LV2/LV3 提升 1/2/3 階；MAX 提升 3 階並直接成為特殊單位。效果不累積。',firstStrike:'Boss 進場時：LV1/LV2/LV3 立即受到 2/3/4 傷害；MAX 受到 5 傷害並跳過本次 Boss Queue 行動。',reinforce:'每第 10 名生成英雄：LV1/LV2/LV3 直接生成數字 2/4/8；MAX 生成數字 8 的特殊單位。',mutation:'新英雄生成時成為特殊單位的機率：LV1 10%、LV2 20%、LV3 30%、MAX 40%。',risk:'擊殺敵人得分固定 ×2；我方死亡扣分：LV1 ×4、LV2 ×3.5、LV3 ×3、MAX ×2.5。扣分無條件進位，SCORE 最低為 0。',assault:'對 Boss 造成的每次傷害額外增加：LV1 +1、LV2 +2、LV3 +3、MAX +4。',precision:'每 15 次合併：LV1/LV2/LV3 隨機 3/4/5 名不同敵人各受 1 傷害；MAX 隨機最多 5 名不同敵人各受 2 傷害。',backup:'英雄生成時額外生成 1 名相同數字、相同普通／特殊身分英雄的機率：LV1 5%、LV2 10%、LV3 15%、MAX 20%。沒有空格時不生成、不延後。'};
for(const [sid,text] of Object.entries(desc)){let re=new RegExp("(\\['"+sid+"','[^']+','[^']+'),('[^']*')");src=src.replace(re,"$1,'"+text.replace(/'/g,"\\'")+"'")}
replaceBlock('function chooseProfession(){','function chooseClassSkill(){',`function chooseProfession(){return new Promise(res=>{let ps=Object.values(PROFESSIONS),idx=0;let detail=p=>p.id==='warrior'?[['⚔️ 迎戰','特殊戰士接觸敵人時，對接觸的敵人造成 1 點傷害。'],['突進','特殊戰士實際移動後接觸敵人時發動近戰攻擊。']]:p.id==='ranger'?[['🏹 遠射','遊俠實際移動後，有 50% 機率對周圍 8 格以外最遠的敵人造成 1 點傷害。'],['↩️ 回身射擊','遊俠移動後，向本次移動的反方向射擊；該方向有敵人時攻擊第一個敵人。']]:[['✨ 治癒波','特殊祭司進場時，治療周圍 8 格內的我方單位 1 HP。'],['🛡️ 守護','祭司實際移動後，自己與周圍 8 格內友方獲得守護；下一次受到傷害時傷害 -1，之後消耗。']];let draw=()=>{let p=ps[idx],skills=detail(p);panel.innerHTML='<h2>選擇特殊職業</h2><div class="lead">第一次合併 · 本局職業一旦選擇就固定</div><div class="professionTabs">'+ps.map((x,i)=>'<button class="professionTab '+(i===idx?'active':'')+'" data-i="'+i+'">'+x.icon+' '+x.name+'</button>').join('')+'</div><div class="professionSwipe"><div class="professionHero"><span>'+p.icon+'</span><div><h3>'+p.name+'</h3><p>'+p.desc+'</p></div></div><div class="professionBasics">'+skills.map(s=>'<div class="professionBasic"><b>'+s[0]+'</b><p>'+s[1]+'</p></div>').join('')+'</div><div class="professionFixed">職業基礎技能為固定能力，不計技能熟練度／等級。</div><button class="professionSelect" data-id="'+p.id+'">選擇 '+p.icon+' '+p.name+'</button><div class="professionSwipeHint">左右滑動切換職業</div></div>';panel.querySelectorAll('.professionTab').forEach(b=>b.onclick=()=>{idx=Number(b.dataset.i);draw()});panel.querySelector('.professionSelect').onclick=b=>{profession=b.currentTarget.dataset.id;classChosen=true;nextSpecial=true;modal.classList.remove('show');render();res()};let area=panel.querySelector('.professionSwipe'),sx=0,sy=0;area.addEventListener('touchstart',e=>{let t=e.changedTouches[0];sx=t.clientX;sy=t.clientY},{passive:true});area.addEventListener('touchend',e=>{let t=e.changedTouches[0],dx=t.clientX-sx,dy=t.clientY-sy;if(Math.abs(dx)>=50&&Math.abs(dx)>Math.abs(dy)*1.2){let ni=idx+(dx<0?1:-1);if(ni>=0&&ni<ps.length){idx=ni;draw()}}},{passive:true})};modal.classList.add('show');draw()})}`);
replaceBlock('function canMove(){','async function mergeFx',`function canMove(){return['left','right','up','down'].some(d=>{let p=plan(d);return p.ms.length>0||p.mids.length>0})}`);
// Mastery-aware spawning.
replaceBlock('function shouldSpawnSpecial(){','function addEnemy(boss=false)',`function shouldSpawnSpecial(){if(!profession)return false;if(awakened)return true;if(nextSpecial){nextSpecial=false;return true}if(scoreSpecialReady())return true;if(has('mutation')){let chance=[.10,.20,.30,.40][rankLevel('mutation')-1];if(Math.random()<chance){useSkill('mutation');return true}}if(reincarnateQueue>0){reincarnateQueue--;return true}return false}
function makeHero(tier=2,forcedSpecial=null,reincarnated=false){let a=empty();if(!a.length)return null;spawn++;let skill=null,forcedByReinforce=false;if(has('reinforce')&&spawn%10===0){let lvl=rankLevel('reinforce');tier=[4,8,16,16][lvl-1];forcedByReinforce=lvl>=4;skill='reinforce'}if(bloodReady){let lvl=rankLevel('blood');tier*=Math.pow(2,Math.min(lvl,3));if(lvl>=4)forcedByReinforce=true;bloodReady=false;deathCount=0;skill='blood'}else if(luckReady){luckReady=false;let chance=[.25,.50,.75,1][rankLevel('luck')-1];if(Math.random()<chance){tier*=2;skill='luck';useSkill('luck')}}let special=forcedSpecial===null?(forcedByReinforce?true:shouldSpawnSpecial()):forcedSpecial,p=randomItem(a),h={id:id++,type:'hero',tier,r:p[0],c:p[1],hits:0,special:!!special,profession:special?profession:null,revived:false,guard:false,guardBy:null,reincarnateEligible:!!special&&!reincarnated};E.push(h);return{e:h,skill}}
function addHero(){let first=makeHero();if(!first)return[];let out=[first];if(has('backup')&&empty().length){let chance=[.05,.10,.15,.20][rankLevel('backup')-1];if(Math.random()<chance){let second=makeHero(first.e.tier,first.e.special,!first.e.reincarnateEligible);if(second){second.skill='backup';out.push(second);useSkill('backup')}}}return out}`);
// Assault scales +1/+2/+3/+4.
replaceBlock('function hitEnemy(e,n,ev,sid,icon=', 'function punishTargets', `function hitEnemy(e,n,ev,sid,icon='✨',source=null,arrow=false){if(!e||e.type==='hero'||rem(e)<=0)return;if(e.type==='boss'&&has('assault')){n+=rankLevel('assault');useSkill('assault')}let d=Math.min(n,rem(e));e.hits+=d;ev.push({t:'damage',e,n:d,s:sid,icon,source,arrow})}`);
// Death skills and score settlement.
replaceBlock('function deathTriggerEvents(wave){','function tryResurrect(hero)',`function deathTriggerEvents(wave){let ev=[];for(let e of wave){if(e.type!=='hero')continue;if(has('deathBlast')){let es=livingEnemies().filter(x=>Math.abs(x.r-e.r)<=1&&Math.abs(x.c-e.c)<=1),lvl=rankLevel('deathBlast'),targets=lvl>=4?es:randomTargets(es,lvl);if(targets.length){for(let x of targets)hitEnemy(x,sdmg(),ev,'deathBlast','💣');useSkill('deathBlast')}}if(has('legacy')){if(!legacy)useSkill('legacy');legacy=true;ev.push({t:'board',icon:'👻 遺志已準備'})}}return ev}`);
replaceBlock('async function processDeathWave(){','async function settle(ev)',`async function processDeathWave(){let candidates=E.filter(e=>rem(e)<=0&&!e.resolvedDeath),rev=[],revived=[];for(let e of candidates){if(e.type==='hero'){let r=tryResurrect(e);if(r){rev.push(r);revived.push(e)}}}if(rev.length)await effectStage(rev);for(let h of revived)if(h.special&&rem(h)>0)await onSpecialEnter(h);let wave=E.filter(e=>rem(e)<=0&&!e.resolvedDeath);if(!wave.length)return false;let conversions=reviveEnemyConversions(wave);for(let e of wave){e.resolvedDeath=true;deathFx(e)}await wait(DM);let bossKills=0;for(let e of wave){if(e.type==='hero'){heroesLost++;deathCount++;if(e.special&&hasClass('reincarnate')&&e.reincarnateEligible){e.reincarnateEligible=false;reincarnateQueue++;useSkill('reincarnate')}if(has('blood')&&deathCount>=3&&!bloodReady){bloodReady=true;useSkill('blood')}let mult=has('risk')?[4,3.5,3,2.5][rankLevel('risk')-1]:1,loss=Math.ceil(hv(e)*mult);loss=Math.min(score,loss);if(has('risk')&&loss>0)useSkill('risk');score=Math.max(0,score-loss);deathPenalty+=loss}else{enemyDefeated++;let riskOn=has('risk');if(e.type==='boss'){let gain=riskOn?200:100;score+=gain;bossScore+=gain;bd++;bl++;bactive=false;next=turn+BI;bossKills++}else{let gain=riskOn?40:20;score+=gain;enemyScore+=gain}if(riskOn)useSkill('risk')}}E=E.filter(e=>!e.resolvedDeath);for(let c of conversions){if(at(c.r,c.c))continue;let h={id:id++,type:'hero',tier:16,r:c.r,c:c.c,hits:2,special:false,profession:null,revived:false,guard:false,guardBy:null,reincarnateEligible:false};E.push(h);render();spawnFx(h,'priestRevive');await wait(TIMING.SPAWN)}render();let ev=deathTriggerEvents(wave);if(ev.length)await effectStage(ev);for(let i=0;i<bossKills;i++)if(profession)await chooseClassSkill();maybeAwaken();return true}`);
// Merge-triggered general mastery.
replaceBlock('function mergeEvents(ids,moved){','function enemyPlan(){',`function mergeEvents(ids,moved){let ev=[],records=[];for(let mid of ids){let h=E.find(x=>x.id===mid);if(!h)continue;merges++;let v=hv(h);score+=v;mergeScore+=v;if(has('resonance')&&merges%5===0){let lvl=rankLevel('resonance'),es=livingEnemies(),targets=lvl>=4?es:randomTargets(es,lvl+2);for(let e of targets)hitEnemy(e,1,ev,'resonance','💥');if(targets.length)useSkill('resonance')}if(has('precision')&&merges%15===0){let lvl=rankLevel('precision'),targets=randomTargets(livingEnemies(),Math.min(lvl+2,5)),d=lvl>=4?2:1;for(let e of targets)hitEnemy(e,d,ev,'precision','📐');if(targets.length)useSkill('precision')}if(legacy){let lvl=rankLevel('legacy'),es=livingEnemies(),targets=lvl>=4?es:randomTargets(es,lvl);for(let e of targets)hitEnemy(e,1,ev,'legacy','👻');legacy=false}if(v>best){best=v;RPGSave.recordBestHero(v);records.push(v)}}if(has('overload')&&ids.length>=2){let lvl=rankLevel('overload'),d=lvl>=4?ids.length:lvl,targets=livingEnemies();for(let e of targets)hitEnemy(e,d,ev,'overload','🔥');if(lvl>=4){for(let h of livingHeroes()){h.guard=true;h.guardBy=null;ev.push({t:'buff',e:h,text:'🛡️ 守護'})}}if(targets.length||lvl>=4)useSkill('overload')}if(has('wind')){let lvl=rankLevel('wind'),threshold=lvl>=3?3:4;if(moved>=threshold){let es=livingEnemies(),targets=lvl>=4?es:randomTargets(es,lvl===1?1:2);for(let e of targets)hitEnemy(e,1,ev,'wind','🌪️');if(targets.length)useSkill('wind')}}return{ev,records}}`);
// Enemy phase: mastery-aware First Strike and Swift MAX.
replaceBlock('function enemyPlan(){','async function move(d)',`async function enemyAct(e){if(!e||rem(e)<=0)return;let hs=livingHeroes();if(!hs.length)return;let adjacent=hs.filter(h=>Math.abs(h.r-e.r)+Math.abs(h.c-e.c)===1).sort((a,b)=>a.id-b.id);if(!adjacent.length){hs=hs.slice().sort((a,b)=>(Math.abs(a.r-e.r)+Math.abs(a.c-e.c))-(Math.abs(b.r-e.r)+Math.abs(b.c-e.c))||a.id-b.id);let h=hs[0],opts=[[Math.sign(h.r-e.r),0],[0,Math.sign(h.c-e.c)]],sr=e.r,sc=e.c;for(let[rr,cc]of opts){let nr=e.r+rr,nc=e.c+cc;if((rr||cc)&&nr>=0&&nr<N&&nc>=0&&nc<N&&!at(nr,nc,e.id)){let m=rec(e,sr,sc,nr,nc);e.r=nr;e.c=nc;render();await animateMoves([m]);render();break}}adjacent=livingHeroes().filter(h=>Math.abs(h.r-e.r)+Math.abs(h.c-e.c)===1).sort((a,b)=>a.id-b.id)}if(adjacent.length&&rem(e)>0){let ev=[];hitHero(adjacent[0],e.damage,e,ev);await settle(ev)}}
async function spawnEnemyPhase(){let swiftMaxSkip=false;if(skipEnemy){skipEnemy=false;swiftMaxSkip=has('swift')&&rankLevel('swift')>=4;trig('swift','👟 疾行')}else if(turn%2===0){let e=addEnemy();if(e){render();spawnFx(e);await wait(TIMING.SPAWN)}}let skipBossId=null;if(turn>=next&&!bactive){let b=addEnemy(true);if(b){bactive=true;render();spawnFx(b);await wait(TIMING.SPAWN);if(has('firstStrike')){let lvl=rankLevel('firstStrike'),be=[];hitEnemy(b,lvl+1,be,'firstStrike','⚡');await settle(be);if(lvl>=4&&rem(b)>0)skipBossId=b.id}}}return{swiftMaxSkip,skipBossId}}
async function enemyPhase(){let phase=await spawnEnemyPhase(),normals=livingEnemies().filter(e=>e.type==='enemy').sort((a,b)=>a.id-b.id).map(e=>e.id),bosses=livingEnemies().filter(e=>e.type==='boss').sort((a,b)=>a.id-b.id).map(e=>e.id);if(!phase.swiftMaxSkip)for(let eid of normals){let e=E.find(x=>x.id===eid);if(e&&rem(e)>0)await enemyAct(e);if(!livingHeroes().length)return}for(let eid of bosses){if(eid===phase.skipBossId)continue;let e=E.find(x=>x.id===eid);if(e&&rem(e)>0)await enemyAct(e);if(!livingHeroes().length)return}}
async function playerPhaseStart(){let hs=addHero();for(let h of hs){render();spawnFx(h.e,h.skill);await wait(TIMING.SPAWN);if(h.e.special)await onSpecialEnter(h.e)}render();check()}`);
// Player action: collision only blocks. General mastery counters are evaluated here.
replaceBlock('async function move(d){','function check(){',`async function move(d){if(ended||busy||modal.classList.contains('show'))return;let p=plan(d);if(!(p.ms.length||p.mids.length)){check();render();return}busy=true;moves++;score++;moveScore++;if(has('swift')){let need=[5,4,3,3][rankLevel('swift')-1];if(moves%need===0)skipEnemy=true}if(has('luck')&&moves%10===0)luckReady=true;await animateMoves(p.ms);E=p.L;render();await mergeFx(p.mids);let chargeEv=warriorChargeEvents(p.moveMeta);if(chargeEv.length)await settle(chargeEv);let moveEv=moveClassEvents(p.moveMeta,d);if(moveEv.length)await settle(moveEv);let mr=mergeEvents(p.mids,p.ms.length);if(mr.ev.length)await settle(mr.ev);let mergeEv=mergeClassEvents(p.mergeMeta);if(mergeEv.length)await settle(mergeEv);if(p.mids.length&&!classChosen)await chooseProfession();for(let v of mr.records)await chooseGeneral(v);noMerge=p.mids.length?0:noMerge+1;if(has('momentum')&&noMerge>=3){let lvl=rankLevel('momentum'),me=[];for(let h of livingHeroes()){heal(h,Math.min(lvl,3),me,'momentum');if(lvl>=4){h.guard=true;h.guardBy=null;me.push({t:'buff',e:h,text:'🛡️ 守護'})}}noMerge=0;if(me.length){useSkill('momentum');await settle(me)}}maybeAwaken();if(!livingHeroes().length){check();busy=false;return}await enemyPhase();if(!livingHeroes().length){check();busy=false;return}turn++;await playerPhaseStart();render();busy=false}`);
replaceBlock('function reset(){','bindDirectionalInput(',`function reset(){E=[];turn=0;merges=0;id=1;ended=false;busy=false;score=0;moves=0;best=1;bl=1;bd=0;next=20;bactive=false,spawn=0,noMerge=0,legacy=false,sel=[],classSel=[],profession=null,classChosen=false,nextSpecial=false,awakened=false,reincarnateQueue=0,claimedScoreMilestone=0,specialMilestoneQueue=0,moveScore=0,mergeScore=0,enemyScore=0,bossScore=0,deathPenalty=0,heroesLost=0,enemyDefeated=0,deathCount=0,bloodReady=false,skipEnemy=false,luckReady=false;effects.innerHTML='';modal.classList.remove('show');makeHero(2,false);makeHero(2,false);makeHero(2,false);render();check()}`);
(0,eval)(src+'\n//# sourceURL=rpg-v2-v0-6/game-v06-runtime.js');
}).catch(e=>fail(e.message));
})();