(function(){'use strict';
const bootError=document.getElementById('bootError');
function fail(msg){if(bootError){bootError.style.display='block';bootError.textContent='v0.6 HP 模組載入失敗：'+msg}console.error(msg)}
fetch('game.js?v=20260915b').then(r=>{if(!r.ok)throw new Error('game.js '+r.status);return r.text()}).then(src=>{
const patches=[
["hv=e=>(e.tier||2)/2,max=e=>e.type==='hero'?e.tier:e.maxHits,rem=e=>Math.max(0,max(e)-(e.hits||0))","hv=e=>(e.tier||2)/2,heroMax=tier=>1+Math.log2(Math.max(2,tier||2)),enemyMax=()=>Math.ceil((bd+1)/2),max=e=>e.type==='hero'?heroMax(e.tier):e.maxHits,rem=e=>Math.max(0,max(e)-(e.hits||0))"],
["healthBar(rem(e),e.tier,'hero')","healthBar(rem(e),max(e),'hero')"],
["return '<div class=\"icon\">🥷</div><div class=\"name\">暗影刺客</div><div class=\"unitMeta\">ATK '+e.damage+'</div>'","return '<div class=\"icon\">🥷</div><div class=\"name\">暗影刺客</div>'+(e.maxHits>1?healthBar(rem(e),e.maxHits,'enemy','ATK '+e.damage):'<div class=\"unitMeta\">ATK '+e.damage+'</div>')"],
["maxHits:boss?bmax():1,damage:boss?bdmg():edmg()","maxHits:boss?bmax():enemyMax(),damage:boss?bdmg():edmg()"],
["let r=Math.min(nt,rem(o)+rem(h));ms.push(rec(h,sr,sc,o.r,o.c));o.tier=nt;o.hits=Math.max(0,nt-r);","let r=Math.min(heroMax(nt),rem(o)+rem(h));ms.push(rec(h,sr,sc,o.r,o.c));o.tier=nt;o.hits=Math.max(0,heroMax(nt)-r);"],
["tier:16,r:c.r,c:c.c,hits:13,special:false","tier:16,r:c.r,c:c.c,hits:2,special:false"],
["};fireFarshot('rangerFarshot');if(hasClass('rangerQuickShot'))","};if(Math.random()<.50)fireFarshot('rangerFarshot');if(hasClass('rangerQuickShot'))"],
["function chooseProfession(){return new Promise(res=>{panel.innerHTML='<h2>選擇特殊職業</h2><div class=\"lead\">第一次合併 · 本局職業一旦選擇就固定</div><div class=\"choices\">'+Object.values(PROFESSIONS).map(p=>'<button class=\"choice\" data-id=\"'+p.id+'\"><span class=\"emoji\">'+p.icon+'</span><strong>'+p.name+'</strong><span>'+p.desc+'<br>進場：'+p.entry+'｜移動：'+p.move+'<br><small>職業基本能力不計技能等級</small></span></button>').join('')+'</div>';modal.classList.add('show');panel.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{profession=b.dataset.id;classChosen=true;nextSpecial=true;modal.classList.remove('show');render();res()})})}","function chooseProfession(){return new Promise(res=>{let ps=Object.values(PROFESSIONS),idx=0;let detail=p=>p.id==='warrior'?[['⚔️ 迎戰','特殊戰士接觸敵人時，對接觸的敵人造成 1 點傷害。'],['突進','特殊戰士實際移動後接觸敵人時發動近戰攻擊。']]:p.id==='ranger'?[['🏹 遠射','遊俠實際移動後，有 50% 機率對周圍 8 格以外最遠的敵人造成 1 點傷害。'],['↩️ 回身射擊','遊俠移動後，向本次移動的反方向射擊；該方向有敵人時攻擊第一個敵人。']]:[['✨ 治癒波','特殊祭司進場時，治療周圍 8 格內的我方單位 1 HP。'],['🛡️ 守護','祭司實際移動後，自己與周圍 8 格內友方獲得守護；下一次受到攻擊時傷害 -1，之後消耗。']];let draw=()=>{let p=ps[idx],skills=detail(p);panel.innerHTML='<h2>選擇特殊職業</h2><div class=\"lead\">第一次合併 · 本局職業一旦選擇就固定</div><div class=\"professionTabs\">'+ps.map((x,i)=>'<button class=\"professionTab '+(i===idx?'active':'')+'\" data-i=\"'+i+'\">'+x.icon+' '+x.name+'</button>').join('')+'</div><div class=\"professionSwipe\"><div class=\"professionHero\"><span>'+p.icon+'</span><div><h3>'+p.name+'</h3><p>'+p.desc+'</p></div></div><div class=\"professionBasics\">'+skills.map(s=>'<div class=\"professionBasic\"><b>'+s[0]+'</b><p>'+s[1]+'</p></div>').join('')+'</div><div class=\"professionFixed\">職業基礎技能為固定能力，不計技能熟練度／等級。</div><button class=\"professionSelect\" data-id=\"'+p.id+'\">選擇 '+p.icon+' '+p.name+'</button><div class=\"professionSwipeHint\">左右滑動切換職業</div></div>';panel.querySelectorAll('.professionTab').forEach(b=>b.onclick=()=>{idx=Number(b.dataset.i);draw()});panel.querySelector('.professionSelect').onclick=b=>{profession=b.currentTarget.dataset.id;classChosen=true;nextSpecial=true;modal.classList.remove('show');render();res()};let area=panel.querySelector('.professionSwipe'),sx=0,sy=0;area.addEventListener('touchstart',e=>{let t=e.changedTouches[0];sx=t.clientX;sy=t.clientY},{passive:true});area.addEventListener('touchend',e=>{let t=e.changedTouches[0],dx=t.clientX-sx,dy=t.clientY-sy;if(Math.abs(dx)>=50&&Math.abs(dx)>Math.abs(dy)*1.2){let ni=idx+(dx<0?1:-1);if(ni>=0&&ni<ps.length){idx=ni;draw()}}},{passive:true})};modal.classList.add('show');draw()})}"],
["window.__V2_TEST__={hv,max,rem,plan","window.__V2_TEST__={hv,heroMax,enemyMax,max,rem,plan"]
];
for(const [from,to] of patches){if(!src.includes(from))throw new Error('找不到預期的 HP 程式片段');src=src.replace(from,to)}
(0,eval)(src+'\n//# sourceURL=rpg-v2-v0-6/game-hp-runtime.js');
}).catch(e=>fail(e.message));
})();