(function(){'use strict';
const {TIMING,randomItem,emptyCells,healthBar,bindDirectionalInput,renderRunHistory}=RPGShared;
const N=4,BI=20,MM=TIMING.MOVE,GM=TIMING.MERGE,FX=TIMING.EFFECT,DM=TIMING.DEATH;
const $=id=>document.getElementById(id),grid=$('grid'),pieces=$('pieces'),effects=$('effects'),board=$('board'),modal=$('modal'),panel=$('panel'),icons=$('skillIcons');for(let i=0;i<16;i++){let d=document.createElement('div');d.className='cell';grid.appendChild(d)}
const S=[['swift','⚡','疾行','每 5 次有效移動，隨機 1 名敵人受到 1 傷害。'],['wind','🌪️','風壓','一次滑動移動至少 3 名英雄時，隨機 1 名敵人受到 1 傷害。'],['momentum','👣','餘勢','連續 3 回合沒有合併，第 3 回合所有英雄恢復 1 HP。'],['resonance','💥','共鳴','每 3 次合併，所有敵人受到 1 傷害。'],['fusionHeal','🌱','融合再生','合併完成後，新英雄恢復 1 HP。'],['overload','✨','超載','同一次滑動發生 2 次以上合併，所有敵人受到 1 傷害。'],['thorns','🛡️','反震','英雄受到敵人攻擊時，攻擊者受到 1 傷害。'],['adversity','🩸','逆境','英雄 HP 首次降到一半以下時，隨機敵人受到 1 傷害。'],['rage','🔥','怒火','每累積承受 5 HP 傷害，下一次技能傷害 +1。'],['deathBlast','💣','遺爆','英雄死亡時，周圍 8 格敵人受到 1 傷害。'],['legacy','👻','遺志','英雄死亡後，下一次合併額外攻擊 1 名隨機敵人。'],['blood','🩸','血祭','英雄死亡後，下一次技能傷害 +1。'],['harvest','🌑','靈魂收割','每擊殺 3 名敵人，隨機英雄恢復 1 HP。'],['chainKill','⚔️','連殺','同一死亡波擊殺 2 名以上敵人時，再隨機攻擊 1 名敵人。'],['killingIntent','🔴','殺意','每累積擊殺 5 名敵人，下一次技能傷害 +1。'],['prepare','✨','決戰準備','Boss 出現時，所有英雄恢復 1 HP。'],['firstStrike','⚡','先制','Boss 出現時立即受到 2 傷害。'],['fortress','🏰','堡壘','Boss 出現後前 3 回合，英雄受到的傷害 -1。'],['reinforce','🌟','優質增援','每生成 5 名英雄，第 5 名直接以數字 2 出現。'],['newborn','❤️','新生','新生成英雄第一次受到傷害時，傷害 -1。'],['mutation','🎲','突變','新英雄有 10% 機率直接生成數字 2。'],['lone','🐺','孤軍','場上英雄 ≤3 時，技能造成的傷害 +1。'],['crowd','🧱','人海','場上英雄 ≥6 時，每 5 回合隨機英雄恢復 1 HP。'],['crisis','🚨','危機感知','棋盤空格 ≤3 時，每次合併額外恢復該英雄 1 HP。'],['breaker','👑','突破者','每次創造新的最高英雄數字，額外獲得該數字 ×5 Score。'],['bossHunter','🏆','獵王','擊敗 Boss 的分數由 +100 提升為 +150。'],['risk','💎','高風險投資','敵人擊殺分數 ×2，但英雄死亡扣分也 ×2。']].map(x=>({id:x[0],icon:x[1],name:x[2],desc:x[3]}));
let E=[],turn=0,merges=0,id=1,ended=false,busy=false,score=0,moves=0,best=1,bl=1,bd=0,next=20,bactive=false,spawn=0,noMerge=0,taken=0,boost=0,legacy=false,shield=-1,sel=[],kills=0,moveScore=0,mergeScore=0,enemyScore=0,bossScore=0,deathPenalty=0,heroesLost=0,enemyDefeated=0;
const wait=n=>new Promise(r=>setTimeout(r,n)),has=x=>sel.includes(x),bmax=()=>10+(bl-1)*5,edmg=()=>Math.ceil((bd+1)/2),bdmg=()=>Math.ceil(bl/2),hv=e=>(e.tier||2)/2,max=e=>e.type==='hero'?e.tier:e.maxHits,rem=e=>Math.max(0,max(e)-(e.hits||0));
function empty(){return emptyCells(E,N)}function at(r,c,skip,list=E){return list.find(x=>x.id!==skip&&x.r===r&&x.c===c)}function step(){return(pieces.clientWidth-24)/4+8}function cls(e){return e.type==='hero'?'heroUnit':e.type==='boss'?'boss':'enemy'}
const anim=RPGAnimations.createAnimator({effects,step});
function inner(e){if(e.type==='hero')return '<div class="heroNum">'+hv(e)+'</div>'+healthBar(rem(e),e.tier,'hero');if(e.type==='boss')return '<div class="icon">👑</div><div class="name">Boss</div>'+healthBar(rem(e),e.maxHits,'boss','ATK '+e.damage);return '<div class="icon">🥷</div><div class="name">暗影刺客</div><div class="unitMeta">ATK '+e.damage+'</div>'}
function addHero(){let a=empty();if(!a.length)return null;spawn++;let tier=2,skill=null;if(has('reinforce')&&spawn%5===0){tier=4;skill='reinforce'}else if(has('mutation')&&Math.random()<.1){tier=4;skill='mutation'}let p=randomItem(a),r=p[0],c=p[1],h={id:id++,type:'hero',tier,r,c,hits:0,newborn:true};E.push(h);return{e:h,skill}}
function addEnemy(boss=false){let a=empty();if(!a.length)return null;let p=randomItem(a),r=p[0],c=p[1],e={id:id++,type:boss?'boss':'enemy',r,c,hits:0,maxHits:boss?bmax():1,damage:boss?bdmg():edmg()};E.push(e);return e}
function renderIcons(){icons.innerHTML='';if(!sel.length){icons.innerHTML='<div class="empty-skills">尚未取得技能</div>';return}for(let sid of sel){let s=S.find(x=>x.id===sid),b=document.createElement('button');b.className='skill-icon';b.dataset.s=sid;b.textContent=s.icon;b.onclick=()=>detail(s);icons.appendChild(b)}}
function render(){pieces.innerHTML='';let s=step();for(let e of E){let d=document.createElement('div');d.className='piece '+cls(e);d.dataset.id=e.id;d.style.transform='translate('+(e.c*s)+'px,'+(e.r*s)+'px)';d.innerHTML=inner(e);pieces.appendChild(d)}$('score').textContent=score;$('turn').textContent=turn;$('merges').textContent=merges;$('best').textContent=best;renderIcons()}
function detail(s){panel.innerHTML='<div class="detail"><div class="big">'+s.icon+'</div><h2>'+s.name+'</h2><p>'+s.desc+'</p><button class="close">關閉</button></div>';modal.classList.add('show');panel.querySelector('.close').onclick=()=>modal.classList.remove('show')}
function choose(v){return new Promise(res=>{let p=S.filter(s=>!sel.includes(s.id)),o=[];while(p.length&&o.length<3)o.push(p.splice(Math.floor(Math.random()*p.length),1)[0]);if(!o.length){res();return}panel.innerHTML='<h2>NEW HERO '+v+'</h2><div class="lead">突破新的最高數字 · 選擇 1 個全局技能</div><div class="choices">'+o.map(s=>'<button class="choice" data-id="'+s.id+'"><span class="emoji">'+s.icon+'</span><strong>'+s.name+'</strong><span>'+s.desc+'</span></button>').join('')+'</div>';modal.classList.add('show');panel.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{sel.push(b.dataset.id);modal.classList.remove('show');renderIcons();res()})})}
function trig(sid,label){let s=S.find(x=>x.id===sid);if(!s)return;let b=icons.querySelector('[data-s="'+sid+'"]');if(b)anim.play('pulse',{element:b});anim.play('skill-tag',{text:label||s.icon+' '+s.name})}
function boardFx(icon,sid){anim.play('board-wave');trig(sid,icon)}
function deathFx(e){let d=document.createElement('div'),s=step();d.className='deathfx '+cls(e);d.style.transform='translate('+(e.c*s)+'px,'+(e.r*s)+'px)';d.innerHTML=inner(e);effects.appendChild(d);setTimeout(()=>d.remove(),DM)}function spawnFx(e,sid){let d=document.createElement('div'),s=step();d.className='spawnfx '+cls(e);d.style.transform='translate('+(e.c*s)+'px,'+(e.r*s)+'px)';d.innerHTML=inner(e);effects.appendChild(d);if(sid)trig(sid);setTimeout(()=>d.remove(),TIMING.SPAWN)}
function heal(e,n,ev,sid){if(!e||e.type!=='hero')return;let b=e.hits;e.hits=Math.max(0,(e.hits||0)-n);let h=b-e.hits;if(h)ev.push({t:'heal',e,n:h,s:sid})}function sdmg(){let d=1+(has('lone')&&E.filter(x=>x.type==='hero'&&rem(x)>0).length<=3?1:0)+boost;boost=0;return d}
function hitEnemy(e,n,ev,sid,icon='✨'){if(!e||e.type==='hero'||rem(e)<=0)return;let d=Math.min(n,rem(e));e.hits+=d;ev.push({t:'damage',e,n:d,s:sid,icon})}
function hitHero(h,n,a,ev){if(!h||rem(h)<=0)return;let d=n;if(has('fortress')&&turn<=shield){let x=d;d=Math.max(0,d-1);if(d<x)ev.push({t:'buff',e:h,text:'-1',s:'fortress'})}if(has('newborn')&&h.newborn){let x=d;d=Math.max(0,d-1);h.newborn=false;if(d<x)ev.push({t:'buff',e:h,text:'-1',s:'newborn'})}d=Math.min(d,rem(h));h.hits+=d;if(d)ev.push({t:'damage',e:h,n:d,icon:'slash',enemyAttack:true});taken+=d;if(has('rage')&&taken>=5){taken-=5;boost++;ev.push({t:'buff',e:h,text:'+DMG',s:'rage'})}if(has('thorns')&&a&&rem(a)>0)hitEnemy(a,1,ev,'thorns','🛡️');if(has('adversity')&&!h.adv&&rem(h)>0&&rem(h)<=h.tier/2){h.adv=true;let es=E.filter(x=>x.type!=='hero'&&rem(x)>0);if(es.length)hitEnemy(randomItem(es),sdmg(),ev,'adversity','🩸')}}
async function effectStage(ev){if(!ev.length)return;let ss=new Set;for(let x of ev){if(x.s)ss.add(x.s);if(x.t==='damage'){if(x.enemyAttack||x.icon==='slash')anim.play('slash',{target:x.e});else anim.play('burst',{target:x.e,icon:x.icon||'✨'});anim.play('damage',{target:x.e,value:x.n})}else if(x.t==='heal')anim.play('heal',{target:x.e,value:x.n});else if(x.t==='buff')anim.play('buff',{target:x.e,text:x.text});else if(x.t==='board')boardFx(x.icon,x.s)}for(let s of ss)trig(s);render();await wait(FX)}
function deathTriggerEvents(deadWave){let ev=[],enemyWaveKills=0;for(let e of deadWave){if(e.type==='hero'){if(has('deathBlast'))for(let q of E.filter(x=>x.type!=='hero'&&rem(x)>0&&Math.abs(x.r-e.r)<=1&&Math.abs(x.c-e.c)<=1))hitEnemy(q,sdmg(),ev,'deathBlast','💣');if(has('legacy')){legacy=true;ev.push({t:'board',icon:'👻',s:'legacy'})}if(has('blood')){boost++;ev.push({t:'board',icon:'🩸 +DMG',s:'blood'})}}else enemyWaveKills++}if(enemyWaveKills&&has('harvest')&&kills%3===0){let hs=E.filter(x=>x.type==='hero'&&rem(x)>0);if(hs.length)heal(randomItem(hs),1,ev,'harvest')}if(enemyWaveKills&&has('killingIntent')&&kills%5===0){boost++;ev.push({t:'board',icon:'🔴 +DMG',s:'killingIntent'})}if(enemyWaveKills>=2&&has('chainKill')){let es=E.filter(x=>x.type!=='hero'&&rem(x)>0);if(es.length)hitEnemy(randomItem(es),sdmg(),ev,'chainKill','⚔️')}return ev}
async function processDeathWave(){let wave=E.filter(e=>rem(e)<=0&&!e.resolvedDeath);if(!wave.length)return false;for(let e of wave){e.resolvedDeath=true;deathFx(e)}await wait(DM);for(let e of wave){if(e.type==='hero'){heroesLost++;let loss=Math.min(score,hv(e)*(has('risk')?2:1));score-=loss;deathPenalty+=loss}else{enemyDefeated++;kills++;if(e.type==='boss'){let gain=has('bossHunter')?150:100;score+=gain;bossScore+=gain;bd++;bl++;bactive=false;next=turn+BI}else{let gain=has('risk')?40:20;score+=gain;enemyScore+=gain}}}E=E.filter(e=>!e.resolvedDeath);render();let ev=deathTriggerEvents(wave);if(ev.length)await effectStage(ev);return true}
async function settle(ev){if(ev.length)await effectStage(ev);for(let guard=0;guard<16;guard++){let had=await processDeathWave();if(!had)break}}
function rec(e,fr,fc,tr,tc){return{id:e.id,fr,fc,tr,tc,cl:cls(e),html:inner(e)}}
async function animateMoves(ms){if(!ms.length)return;let s=step();for(let m of ms){let b=pieces.querySelector('[data-id="'+m.id+'"]');if(b)b.classList.add('hideForMove');let g=document.createElement('div');g.className='moveghost '+m.cl;g.innerHTML=m.html;g.style.transform='translate('+(m.fc*s)+'px,'+(m.fr*s)+'px)';effects.appendChild(g);m.el=g}requestAnimationFrame(()=>requestAnimationFrame(()=>ms.forEach(m=>m.el.style.transform='translate('+(m.tc*s)+'px,'+(m.tr*s)+'px)')));await wait(MM);ms.forEach(m=>m.el.remove())}
function plan(dir){let L=JSON.parse(JSON.stringify(E)),before=JSON.stringify(L.map(x=>[x.id,x.r,x.c,x.tier])),hs=L.filter(x=>x.type==='hero'&&rem(x)>0),dr=dir==='up'?-1:dir==='down'?1:0,dc=dir==='left'?-1:dir==='right'?1:0;hs.sort((a,b)=>dir==='left'?a.c-b.c:dir==='right'?b.c-a.c:dir==='up'?a.r-b.r:b.r-a.r);let merged=new Set,mids=[],ms=[],contacts=[];for(let h of hs){if(!L.some(x=>x.id===h.id))continue;let sr=h.r,sc=h.c;while(1){let nr=h.r+dr,nc=h.c+dc;if(nr<0||nr>=N||nc<0||nc>=N)break;let o=at(nr,nc,h.id,L);if(!o){h.r=nr;h.c=nc;continue}if(o.type==='hero'&&o.tier===h.tier&&!merged.has(o.id)){let nt=o.tier*2,r=Math.min(nt,rem(o)+rem(h));ms.push(rec(h,sr,sc,o.r,o.c));o.tier=nt;o.hits=nt-r;L=L.filter(x=>x.id!==h.id);merged.add(o.id);mids.push(o.id);break}if(o.type!=='hero')contacts.push({h:h.id,e:o.id});break}if(L.some(x=>x.id===h.id)&&(sr!==h.r||sc!==h.c))ms.push(rec(h,sr,sc,h.r,h.c))}return{changed:contacts.length||before!==JSON.stringify(L.map(x=>[x.id,x.r,x.c,x.tier])),L,ms,mids,contacts}}
function canMove(){return['left','right','up','down'].some(d=>plan(d).changed)}
async function mergeFx(ids){if(!ids.length)return;for(let mid of ids){let h=E.find(x=>x.id===mid);if(h){let d=document.createElement('div'),s=step();d.className='mergefx';d.style.transform='translate('+(h.c*s)+'px,'+(h.r*s)+'px)';d.innerHTML=inner(h);effects.appendChild(d);setTimeout(()=>d.remove(),GM)}}await wait(GM)}
function mergeEvents(ids,moved){let ev=[],records=[];for(let mid of ids){let h=E.find(x=>x.id===mid);if(!h)continue;merges++;let v=hv(h);score+=v;mergeScore+=v;if(has('fusionHeal'))heal(h,1,ev,'fusionHeal');if(has('crisis')&&empty().length<=3)heal(h,1,ev,'crisis');if(has('resonance')&&merges%3===0){let d=sdmg();for(let e of E.filter(x=>x.type!=='hero'&&rem(x)>0))hitEnemy(e,d,ev,'resonance','💥')}if(legacy){let es=E.filter(x=>x.type!=='hero'&&rem(x)>0);if(es.length)hitEnemy(randomItem(es),sdmg(),ev,'legacy','👻');legacy=false}if(v>best){best=v;if(has('breaker')){let bonus=v*5;score+=bonus;mergeScore+=bonus;ev.push({t:'board',icon:'👑 +'+bonus,s:'breaker'})}records.push(v)}}if(has('overload')&&ids.length>=2){let d=sdmg();for(let e of E.filter(x=>x.type!=='hero'&&rem(x)>0))hitEnemy(e,d,ev,'overload','✨')}if(has('wind')&&moved>=3){let es=E.filter(x=>x.type!=='hero'&&rem(x)>0);if(es.length)hitEnemy(randomItem(es),sdmg(),ev,'wind','🌪️')}if(has('lone')&&E.filter(x=>x.type==='hero'&&rem(x)>0).length<=3&&ev.some(x=>x.t==='damage'))ev.push({t:'board',icon:'🐺',s:'lone'});return{ev,records}}
function enemyPlan(){let ms=[],att=[];for(let e of E.filter(x=>x.type!=='hero'&&rem(x)>0)){let a=E.find(h=>h.type==='hero'&&rem(h)>0&&Math.abs(h.r-e.r)+Math.abs(h.c-e.c)===1);if(a){att.push({e:e.id,h:a.id});continue}let hs=E.filter(x=>x.type==='hero'&&rem(x)>0);if(!hs.length)break;hs.sort((a,b)=>(Math.abs(a.r-e.r)+Math.abs(a.c-e.c))-(Math.abs(b.r-e.r)+Math.abs(b.c-e.c)));let h=hs[0],opts=[[Math.sign(h.r-e.r),0],[0,Math.sign(h.c-e.c)]],sr=e.r,sc=e.c;for(let[rr,cc]of opts){let nr=e.r+rr,nc=e.c+cc;if((rr||cc)&&nr>=0&&nr<N&&nc>=0&&nc<N&&!at(nr,nc,e.id)){e.r=nr;e.c=nc;ms.push(rec(e,sr,sc,nr,nc));break}}}return{ms,att}}
async function enemyPhase(){let p=enemyPlan();if(p.ms.length){render();await animateMoves(p.ms);render()}let ev=[];for(let a of p.att){let h=E.find(x=>x.id===a.h),e=E.find(x=>x.id===a.e);if(h&&e&&rem(h)>0&&rem(e)>0)hitHero(h,e.damage,e,ev)}await settle(ev)}
async function postTurn(){let ev=[];if(has('crowd')&&E.filter(x=>x.type==='hero'&&rem(x)>0).length>=6&&turn%5===0){let hs=E.filter(x=>x.type==='hero'&&rem(x)>0);if(hs.length)heal(randomItem(hs),1,ev,'crowd')}if(ev.length)await settle(ev);if(turn%2===0){let e=addEnemy();if(e){render();spawnFx(e);await wait(TIMING.SPAWN)}}let h=addHero();if(h){render();spawnFx(h.e,h.skill);await wait(TIMING.SPAWN)}if(turn>=next&&!bactive){let b=addEnemy(true);if(b){bactive=true;render();spawnFx(b);await wait(TIMING.SPAWN);let be=[];if(has('prepare'))for(let x of E.filter(x=>x.type==='hero'&&rem(x)>0))heal(x,1,be,'prepare');if(has('firstStrike'))hitEnemy(b,2,be,'firstStrike','⚡');if(has('fortress')){shield=turn+2;be.push({t:'board',icon:'🏰',s:'fortress'})}await settle(be)}}}
async function move(d){if(ended||busy||modal.classList.contains('show'))return;let p=plan(d);if(!p.changed){check();render();return}busy=true;moves++;score++;moveScore++;await animateMoves(p.ms);E=p.L;render();await mergeFx(p.mids);let ev=[];for(let c of p.contacts){let h=E.find(x=>x.id===c.h),e=E.find(x=>x.id===c.e);if(h&&e)hitHero(h,e.damage,e,ev)}if(has('swift')&&moves%5===0){let es=E.filter(x=>x.type!=='hero'&&rem(x)>0);if(es.length)hitEnemy(randomItem(es),sdmg(),ev,'swift','⚡')}let mr=mergeEvents(p.mids,p.ms.length);ev.push(...mr.ev);await settle(ev);for(let v of mr.records)await choose(v);noMerge=p.mids.length?0:noMerge+1;if(has('momentum')&&noMerge>=3){let me=[];for(let h of E.filter(x=>x.type==='hero'&&rem(x)>0))heal(h,1,me,'momentum');noMerge=0;await settle(me)}if(!E.some(x=>x.type==='hero'&&rem(x)>0)){check();busy=false;return}turn++;render();await enemyPhase();if(!E.some(x=>x.type==='hero'&&rem(x)>0)){check();busy=false;return}await postTurn();render();check();busy=false}
function check(){if(!E.some(x=>x.type==='hero'&&rem(x)>0))return end('隊伍全滅');if(!canMove())return end('無法移動')}
function end(t){if(ended)return;ended=true;let skillHtml=sel.length?sel.map(sid=>{let s=S.find(x=>x.id===sid);return '<div class="resultSkill" title="'+s.desc+'"><b>'+s.icon+'</b><span>'+s.name+'</span></div>'}).join(''):'<div class="noSkill">本局尚未取得技能</div>';let skills='<div class="skillCard"><h3>本局取得技能</h3><div class="resultSkills">'+skillHtml+'</div></div>';panel.innerHTML=renderRunHistory({title:t,score,scoreRows:[{label:'移動得分',value:'+'+moveScore,className:'plus'},{label:'合併／突破得分',value:'+'+mergeScore,className:'plus'},{label:'擊殺暗影刺客',value:'+'+enemyScore,className:'plus'},{label:'擊敗 Boss',value:'+'+bossScore,className:'plus'},{label:'英雄死亡',value:'−'+deathPenalty,className:'minus'}],historyRows:[{label:'存活回合',value:turn},{label:'移動次數',value:moves},{label:'合併次數',value:merges},{label:'擊殺敵人',value:enemyDefeated},{label:'其中 Boss',value:bd},{label:'英雄死亡',value:heroesLost},{label:'最高英雄數字',value:best}],skillsHtml:skills,backHtml:'<a href="../type-01-v2/">回到 Version 2</a>'});modal.classList.add('show');$('again').onclick=reset}
function reset(){E=[];turn=0;merges=0;id=1;ended=false;busy=false;score=0;moves=0;best=1;bl=1;bd=0;next=20;bactive=false;spawn=0;noMerge=0;taken=0;boost=0;legacy=false;shield=-1;sel=[];kills=0;moveScore=0;mergeScore=0;enemyScore=0;bossScore=0;deathPenalty=0;heroesLost=0;enemyDefeated=0;effects.innerHTML='';modal.classList.remove('show');addHero();addHero();addHero();render()}
bindDirectionalInput({board,onMove:move,threshold:25,keyMap:{ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}});window.addEventListener('resize',render);$('restart').onclick=reset;reset();
window.__V2_TEST__={hv,max,rem,plan,mergeEvents,deathTriggerEvents,getSkills:()=>S.slice()};
})();